#!/usr/bin/env python3
"""The part introduction pages (part1/index.md … part7/index.md), from the nav and the chapters.

    python3 manual/tools/gen_indexes.py

Each part page is a short introduction (below, in PARTS) followed by its chapters, each with the
chapter's own "In one sentence" summary — taken from the chapter, so the index cannot drift from it.
"""
import pathlib, re

ROOT = pathlib.Path(__file__).resolve().parents[2]
DOCS = ROOT / "manual" / "docs"
NAV = ROOT / "manual" / "mkdocs.yml"

PARTS = {
    "part1": ("Part I — Getting started",
              "What jayecu is, how to install the studio, a tour of it, the first connection to an ECU, and "
              "a checklist from a new box to a first start. Start here if jayecu is new to you."),
    "part2": ("Part II — Hardware and wiring",
              "The jaytek_v1 board and everything that connects to it: tools, wiring practice, power and "
              "grounds, sensors, outputs, CAN and the rest of the vehicle. Read it before you build or "
              "check a harness."),
    "part3": ("Part III — Configuring the engine",
              "One chapter for each job the ECU does. Each follows the same shape: what it does, how it "
              "works, before you start, setting it up, worked examples, tuning it, diagnostics, "
              "troubleshooting and the full settings reference."),
    "part4": ("Part IV — Tuning",
              "Finding the right numbers on a running engine: the principles, then fuel, ignition, Auto "
              "Tune, knock and logging. Read chapter 37 first."),
    "part5": ("Part V — Testing and troubleshooting",
              "Proving an installation on the bench, reading trouble codes, and finding the cause of a "
              "symptom."),
    "part6": ("Part VI — Firmware and maintenance",
              "Updating the ECU's firmware, recovering an ECU that will not start, keeping tunes and "
              "backups, and changing the studio's pages to suit you."),
    "part7": ("Part VII — Reference",
              "Exact facts, most of them generated from the same definition the studio loads: every "
              "setting, channel, trouble code, trigger wheel, sensor type, output template and Lua "
              "function, with the specifications and a glossary."),
}


def nav_entries():
    """(part, title, path) for every chapter line of the nav, in order."""
    part, out = None, []
    for line in NAV.read_text().splitlines():
        m = re.match(r"\s*-\s*Part\s+(\w+)\s+—", line)
        if m:
            part = {"I": "part1", "II": "part2", "III": "part3", "IV": "part4", "V": "part5",
                    "VI": "part6", "VII": "part7"}.get(m.group(1))
            continue
        m = re.match(r"\s*-\s*(.+?):\s*([\w/.\-]+\.md)", line)
        if m and part and not re.fullmatch(r"part\d/index\.md", m.group(2)):
            out.append((part, m.group(1).strip(), m.group(2)))
    return out


def summary(path):
    text = (DOCS / path).read_text()
    m = re.search(r"\*\*In one sentence:\*\*\s*(.+?)(?:\n\n|\n[^>])", text, re.S)
    if not m:
        return ""
    s = re.sub(r"\n>\s*", " ", m.group(1)).strip()
    return s[0].upper() + s[1:] if s else s


def main():
    entries = nav_entries()
    for part, (title, intro) in PARTS.items():
        rows = [e for e in entries if e[0] == part]
        out = [f"<!-- GENERATED by manual/tools/gen_indexes.py — edit the intro there, the summaries in the chapters. -->\n\n",
               f"# {title}\n\n{intro}\n\n"]
        for _, t, path in rows:
            rel = path.split("/", 1)[1] if path.startswith(part + "/") else "../" + path
            s = summary(path)
            out.append(f"- **[{t}]({rel})**" + (f" — {s}" if s else "") + "\n")
        (DOCS / part / "index.md").write_text("".join(out))
    print(f"indexes: {len(PARTS)} part pages")


if __name__ == "__main__":
    main()
