#!/usr/bin/env python3
"""Every setting, by module — generated for the manual (STANDARD.md §7).

    python3 manual/tools/gen_settings.py            (after `make codegen`)

Reads shared/tuneit-meta.json — the definition the studio itself loads — so the reference says exactly
what the studio shows: the label, the units, the range and default in real units, and the help text
behind the setting's tooltip. Writes one page per settings group to manual/docs/reference/settings/,
plus the index. Chapters pull a group's table in with the snippet include:

    --8<-- "reference/settings/boost.md"

Never edit the output: fix the help text in definition/ecu.schema.yaml (that fixes the studio's tooltip
too), run `make codegen`, then run this again.
"""
import json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parents[2]
META = ROOT / "shared" / "tuneit-meta.json"
OUT = ROOT / "manual" / "docs" / "reference" / "settings"


def load_meta():
    raw = META.read_bytes()
    return json.loads(raw[:-4])            # a .meta is the JSON body plus a 4-byte CRC32 footer


def title_of(group):
    """'lambda_protect' -> 'Lambda Protect'."""
    return " ".join(w.capitalize() for w in group.split("_"))


def cell(text):
    """Text safe inside a Markdown table cell."""
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def real(raw, f):
    """A raw stored number in the units the studio shows it in."""
    v = raw * f.get("scale", 1.0) + f.get("translate", 0.0)
    digits = f.get("digits")
    if digits is None:
        digits = 0 if float(v).is_integer() else 3
    return f"{v:.{digits}f}"


def describe(name, f):
    kind = f.get("type")
    units = f.get("units", "")
    if f.get("options"):
        opts = ", ".join(o for o in f["options"] if o and o != "INVALID")
        rng, default = f"one of: {opts}", ""
        d = f.get("default")
        if isinstance(d, int) and 0 <= d < len(f["options"]):
            default = f["options"][d]
    elif kind == "scalar" and f.get("min") == 0 and f.get("max") == 1 and f.get("scale", 1.0) == 1.0 \
            and not f.get("translate"):
        rng, default = "Off or On", ("On" if f.get("default") == 1 else "Off")
    elif kind == "table":
        rows, cols = f.get("rows", 1), f.get("cols", 1)
        rng = f"{real(f['min'], f)} to {real(f['max'], f)}" if "min" in f and "max" in f else ""
        default = f"{rows} × {cols} table" if rows > 1 else f"{cols}-point curve"
    else:
        rng = f"{real(f['min'], f)} to {real(f['max'], f)}" if "min" in f and "max" in f else ""
        default = real(f["default"], f) if isinstance(f.get("default"), (int, float)) else ""
    return rng, default, units


def settings_of(group, fields):
    rows = []
    for name, f in fields.items():
        if not isinstance(f, dict) or f.get("type") not in ("scalar", "table", "array", "bits"):
            continue
        if f.get("hidden"):
            continue
        rng, default, units = describe(name, f)
        rows.append((f.get("label") or name, f"{group}.{name}", units, rng, default, f.get("help", "")))
    return rows


def page(group, rows):
    """Two columns, not six: a setting's facts stacked in the first, the explanation given the width it
    needs in the second. Six narrow columns broke paths mid-word and squeezed the description into a
    ribbon nobody could read."""
    out = [f"<!-- GENERATED by manual/tools/gen_settings.py from shared/tuneit-meta.json — do not edit. -->",
           "",
           "| Setting | What it does |",
           "|---|---|"]
    for label, path, units, rng, default, help_ in rows:
        facts = [f"**{cell(label)}**", f"`{path}`"]
        if rng:     facts.append(f"Range: {cell(rng)}")
        if default: facts.append(f"Default: {cell(default)}")
        if units:   facts.append(f"Units: {cell(units)}")
        out.append(f"| {'<br>'.join(facts)} | {cell(help_) or '—'} |")
    return "\n".join(out) + "\n"


def main():
    meta = load_meta()
    OUT.mkdir(parents=True, exist_ok=True)
    groups = meta["config"]
    index = ["# Every setting, by module", "",
             "Generated from the definition the studio loads, so it always matches the firmware it was built "
             "with. Each group lists every setting with its path, units, range, default and the same "
             "description the studio shows in its tooltip.", "",
             "| Group | Settings |", "|---|---|"]
    total = 0
    for group in sorted(groups):
        fields = groups[group]
        if not isinstance(fields, dict):
            continue
        rows = settings_of(group, fields)
        if not rows:
            continue
        total += len(rows)
        body = page(group, rows)
        (OUT / f"{group}.md").write_text(f"# {title_of(group)} settings\n\n" + body)
        # The same table without the heading, for chapters to include.
        (OUT / f"_{group}.table.md").write_text(body)
        index.append(f"| [{title_of(group)}]({group}.md) | {len(rows)} |")
    index += ["", f"**{total} settings** in total."]
    missing = sum(1 for g in groups.values() if isinstance(g, dict)
                  for f in g.values() if isinstance(f, dict) and f.get("type") in ("scalar", "table", "array", "bits")
                  and not f.get("hidden") and not f.get("help"))
    (OUT / "index.md").write_text("\n".join(index) + "\n")
    print(f"settings reference: {missing} of {total} have no help text in the schema")
    print(f"settings reference: {total} settings in {len([g for g in groups if isinstance(groups[g], dict)])} groups -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
