#!/usr/bin/env python3
"""The generated reference pages of the manual (Part VII) — STANDARD.md §7.

    python3 manual/tools/gen_reference.py           (after `make codegen`)

Writes, from the definition the studio itself loads (shared/tuneit-meta.json) and the schema:

    manual/docs/reference/channels.md          every output channel
    manual/docs/reference/dtc.md               every trouble code the definition names
    manual/docs/reference/sensor-types.md      every sensor type, and the sensors of each type
    manual/docs/reference/output-templates.md  every output template and its parameters
    manual/docs/reference/lua-api.md           the Lua functions and callbacks
    manual/docs/reference/trigger-wheels.md    the trigger wheel library, each wheel drawn
    manual/docs/img/wheels/<wheel>.svg         …its diagrams

Never edit the output: fix the source (schema help, the meta's own text), run `make codegen`, run this.
"""
import json, pathlib, re

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[2]
META = ROOT / "shared" / "tuneit-meta.json"
SCHEMA = ROOT / "definition" / "ecu.schema.yaml"
DOCS = ROOT / "manual" / "docs"
REF = DOCS / "reference"
WHEELS = DOCS / "img" / "wheels"

HEADER = "<!-- GENERATED by manual/tools/gen_reference.py from shared/tuneit-meta.json — do not edit. -->\n\n"


def load_meta():
    return json.loads(META.read_bytes()[:-4])       # a .meta is the JSON body plus a 4-byte CRC32 footer


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def num(v, digits=None):
    if isinstance(v, (int, float)):
        if digits is not None:
            return f"{v:.{digits}f}"
        return f"{v:g}"
    return str(v)


# ---------------------------------------------------------------------------------------------------
# Output channels
# ---------------------------------------------------------------------------------------------------
def gen_channels(m):
    tel = m["telemetry"]
    groups = {}
    for name, t in tel.items():
        groups.setdefault(t.get("module") or "Other", []).append((name, t))
    out = [HEADER, "# Output channels\n\n",
           "Every channel the ECU sends to the studio, grouped as the studio groups them. The **name** is\n"
           "what you type in an expression (chapter 34), a Lua script (chapter 35), a CAN field (chapter 33)\n"
           "or a log. **Logged** marks the channels in the ECU's default onboard-log set (chapter 42).\n\n",
           f"{len(tel)} channels.\n\n"]
    for g in sorted(groups):
        out.append(f"## {g}\n\n| Channel | Name | Units | Range | Logged |\n|---|---|---|---|---|\n")
        for name, t in sorted(groups[g], key=lambda kv: kv[1].get("label", kv[0]).lower()):
            d = t.get("digits")
            rng = f"{num(t.get('min'), d)} to {num(t.get('max'), d)}" if "min" in t and "max" in t else ""
            out.append(f"| {cell(t.get('label', name))} | `{name}` | {cell(t.get('units', ''))} | {rng} | "
                       f"{'yes' if t.get('datalog') else ''} |\n")
        out.append("\n")
    (REF / "channels.md").write_text("".join(out))


# ---------------------------------------------------------------------------------------------------
# Trouble codes
# ---------------------------------------------------------------------------------------------------
def code_key(c):
    return int(c[1:], 16)


def gen_dtc(m):
    desc = m["dtc_descriptions"]
    cats = m["dtc_categories"]

    def category(code):
        k = code_key(code)
        for c in cats:
            if code_key(c["lo"]) <= k <= code_key(c["hi"]):
                return c["label"]
        return ""

    out = [HEADER, "# Trouble codes\n\n",
           "Every trouble code this firmware's definition names, with the studio's description and the\n"
           "**Status Lamps** category that lights for it. How codes work — severity, active and stored,\n"
           "clearing — is chapter 44.\n\n",
           "Codes **P0xxx** are the standard OBD-II ones; **P1xxx** are this ECU's own. A sensor's own checks\n"
           "(out of range, not assigned …) use the sensor's standard codes where there are any, and codes\n"
           "in **P1000–P15FF** where there are none.\n\n",
           f"{len(desc)} codes.\n\n",
           "| Code | Description | Lamp |\n|---|---|---|\n"]
    for code in sorted(desc, key=code_key):
        out.append(f"| **{code}** | {cell(desc[code])} | {cell(category(code))} |\n")
    (REF / "dtc.md").write_text("".join(out))


# ---------------------------------------------------------------------------------------------------
# Sensor types
# ---------------------------------------------------------------------------------------------------
def gen_sensor_types(schema):
    types = schema["sensor_types"]
    sensors = schema.get("sensors") or []
    by_type = {}
    for s in sensors:
        by_type.setdefault(s.get("type"), []).append(s)
    out = [HEADER, "# Sensor types\n\n",
           "Every sensor has a **type**: what it measures, in which units, over which range, how often it is\n"
           "read, and which checks it can run (chapter 17). The ECU always works in these units; the studio\n"
           "can show others (Preferences ▸ Units).\n\n",
           "| Type | Units | Range | Read at | Checks |\n|---|---|---|---|---|\n"]
    for t in types:
        diags = ", ".join(t.get("diagnostics", []))
        rate = f"{t['update_hz']} Hz" if "update_hz" in t else ""
        out.append(f"| **{t['id']}** | {cell(t.get('units', ''))} | {num(t.get('min'))} to {num(t.get('max'))} | "
                   f"{rate} | {cell(diags)} |\n")
    out.append("\n## The sensors of each type\n\n")
    for t in types:
        ss = by_type.get(t["id"], [])
        if not ss:
            continue
        out.append(f"### {t['id']}\n\n| Sensor | Interfaces |\n|---|---|\n")
        for s in ss:
            out.append(f"| {cell(s.get('name', s['id']))} | {cell(', '.join(s.get('interfaces', [])))} |\n")
        out.append("\n")
    (REF / "sensor-types.md").write_text("".join(out))


# ---------------------------------------------------------------------------------------------------
# Output templates
# ---------------------------------------------------------------------------------------------------
KIND = {0: "PWM", 1: "Digital"}


def gen_output_templates(m):
    out = [HEADER, "# Output templates\n\n",
           "An output template fills in a Generic output for a common job — its conditions, its value and its\n"
           "parameters — through the output's wizard (chapter 18). Everything it sets can be changed\n"
           "afterwards.\n\n"]
    for t in m["output_templates"]:
        out.append(f"## {t['name']}\n\n{cell(t.get('blurb', ''))}\n\n")
        if t.get("detail"):
            out.append(f"{t['detail'].strip()}\n\n")
        out.append(f"Kind: **{KIND.get(t.get('kind'), t.get('kind'))}**.\n\n")
        ps = t.get("params") or []
        if ps:
            out.append("| Parameter | Units | Default | Range | What it does |\n|---|---|---|---|---|\n")
            for p in ps:
                d = p.get("digits")
                out.append(f"| **{cell(p.get('label', p['name']))}** | {cell(p.get('units', ''))} | "
                           f"{num(p.get('default'), d)} | {num(p.get('min'), d)} to {num(p.get('max'), d)} | "
                           f"{cell(p.get('help', ''))} |\n")
            out.append("\n")
    (REF / "output-templates.md").write_text("".join(out))


# ---------------------------------------------------------------------------------------------------
# Lua API
# ---------------------------------------------------------------------------------------------------
def gen_lua(m):
    api = m["lua_api"]
    out = [HEADER, "# Lua API\n\n",
           "The functions a script can call and the functions it can define. Chapter 35 explains how to\n"
           "use them, with examples. `rpm()`, `map()`, `tps()`, `clt()`, `iat()`, `lambda()` and `battery()`\n"
           "return a fixed value when there is no reading; `signalRead` returns `nil`.\n\n",
           "## Functions\n\n| Call | Does |\n|---|---|\n"]
    for f in api.get("functions", []):
        out.append(f"| `{cell(f['sig'])}` | {cell(f.get('doc', ''))} |\n")
    out.append("\n## Callbacks — define these in your script\n\n| Definition | When |\n|---|---|\n")
    for f in api.get("callbacks", []):
        out.append(f"| `{cell(f['sig'])}` | {cell(f.get('doc', ''))} |\n")
    (REF / "lua-api.md").write_text("".join(out))


# ---------------------------------------------------------------------------------------------------
# Trigger wheels — each drawn over one engine cycle
# ---------------------------------------------------------------------------------------------------
def stream_edges(s):
    """Edge positions in degrees over the stream's own span (360 crank, 720 cam), plus the span.

    gap:   `slots` positions; `gaps` lists the present teeth (by index) that are followed by a gap of
           `ratio` tooth periods — so 36-1 is slots 36, ratio 2, gaps [0]. Ratio 0 is evenly spaced.
    seq:   `cell` is the angle from each edge to the next, in tenths of a degree.
    width: one pulse per cycle.
    `repeats` is how many times the pattern repeats per ENGINE CYCLE (720°), as the firmware reads it
    (GenericTriggerBuilder: repeats, else twice for a crank stream and once for a cam stream).
    The edges returned cover the whole 720° cycle; span is 720."""
    span = 720.0
    reps = int(s.get("repeats", 0) or 0) or (2 if s.get("rate", 0) == 0 else 1)
    part = span / reps
    kind = s.get("kind")
    base = []
    if kind == "gap":
        slots, ratio, gaps = int(s["slots"]), int(s.get("ratio", 0)), list(s.get("gaps", []))
        if ratio <= 1 or not gaps:
            base = [i * part / slots for i in range(slots)]
        else:
            present = slots - len(gaps) * (ratio - 1)
            pos = 0
            for i in range(present):
                base.append(pos * part / slots)
                pos += ratio if i in gaps else 1
    elif kind == "seq":
        cells = [c / 10.0 for c in s["cell"]]
        total = sum(cells) or part
        a = 0.0
        for c in cells:
            base.append(a * part / total)
            a += c
    elif kind == "width":
        base = [0.0]
    edges = [r * part + e for r in range(reps) for e in base]
    return edges, span


def wheel_svg(w):
    W, left, right = 1000, 110, 20
    plot = W - left - right
    rows = w["streams"]
    H = 40 + 60 * len(rows) + 30
    x = lambda deg: left + plot * deg / 720.0
    o = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" '
         "font-family=\"system-ui, -apple-system, 'Segoe UI', Ubuntu, sans-serif\" font-size=\"13\">",
         f"<title>{w['name']}</title>",
         "<style>.fg{fill:#1d1f23}.muted{fill:#5f6670}.axis{stroke:#9aa1ab;stroke-width:1;fill:none}"
         ".tooth{fill:#3b82c4}.cam{fill:#d9822b}.grid{stroke:#c9ced6;stroke-width:1;stroke-dasharray:3 4}"
         "@media (prefers-color-scheme: dark){.fg{fill:#e4e6ea}.muted{fill:#9aa1ab}.grid{stroke:#4a5059}}</style>"]
    for deg in range(0, 721, 90):
        o.append(f'<line x1="{x(deg):.1f}" y1="20" x2="{x(deg):.1f}" y2="{H-26}" class="grid"/>')
        o.append(f'<text x="{x(deg):.1f}" y="{H-8}" text-anchor="middle" class="muted">{deg}°</text>')
    for r, s in enumerate(rows):
        y0 = 40 + 60 * r
        cam = s.get("rate", 0) != 0
        label = "cam" if cam else "crank"
        o.append(f'<text x="10" y="{y0+26}" class="fg">{label}</text>')
        o.append(f'<line x1="{left}" y1="{y0+40}" x2="{left+plot}" y2="{y0+40}" class="axis"/>')
        edges, span = stream_edges(s)
        cls = "cam" if cam else "tooth"
        if s.get("kind") == "width":
            o.append(f'<rect x="{x(0):.1f}" y="{y0+10}" width="{plot*20/720:.1f}" height="30" class="{cls}"/>')
            o.append(f'<text x="{x(30):.1f}" y="{y0+30}" class="muted">one pulse per cycle</text>')
            continue
        both = s.get("edge") == 2 and s.get("kind") == "seq"
        for p in range(1):
            off = 0.0
            if both:
                for i in range(0, len(edges) - 1, 2):
                    a, b = edges[i] + off, edges[i + 1] + off
                    o.append(f'<rect x="{x(a):.1f}" y="{y0+10}" width="{max(1.0, x(b)-x(a)):.1f}" height="30" class="{cls}"/>')
            else:
                # Half the SMALLEST spacing between teeth: an average spreads a clustered pattern's
                # teeth into one solid block.
                gaps_ = [b - a for a, b in zip(edges, edges[1:])] + ([span - edges[-1] + edges[0]] if edges else [])
                pitch = min([g for g in gaps_ if g > 0] or [span])
                tw = max(1.0, min(plot * pitch / 720.0 * 0.5, 14.0))
                for e in edges:
                    o.append(f'<rect x="{x(e + off):.1f}" y="{y0+10}" width="{tw:.1f}" height="30" class="{cls}"/>')
    o.append("</svg>")
    return "\n".join(o)


def slug(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def describe(s):
    cam = "cam" if s.get("rate", 0) != 0 else "crank"
    k = s.get("kind")
    reps = int(s.get("repeats", 0) or 0)
    rep = f", {reps} times per engine cycle" if reps else ""
    if k == "gap":
        slots, ratio, gaps = s["slots"], s.get("ratio", 0), s.get("gaps", [])
        if ratio <= 1 or not gaps:
            return f"{cam}: {slots} evenly spaced teeth{rep}"
        missing = len(gaps) * (ratio - 1)
        return f"{cam}: {slots} positions, {slots - missing} teeth, {len(gaps)} gap(s) of {ratio - 1} missing{rep}"
    if k == "seq":
        both = " (both edges)" if s.get("edge") == 2 else ""
        return f"{cam}: {len(s['cell'])} edges at set angles{both}{rep}"
    if k == "width":
        return f"{cam}: one pulse per cycle"
    return f"{cam}: {k}"


def gen_wheels(m):
    WHEELS.mkdir(parents=True, exist_ok=True)
    for f in WHEELS.glob("*.svg"):
        f.unlink()
    out = [HEADER, "# Trigger wheel library\n\n",
           "Every wheel the studio ships in its Trigger Library (chapter 16), drawn over one engine cycle\n"
           "(720°). A crank pattern normally appears twice (once per revolution) and a cam pattern once. The drawing\n"
           "starts at the pattern's reference, not at top dead centre: **Trigger Offset** sets where TDC\n"
           "is (chapter 16). **Crank** sync knows the angle within a revolution; **Phase** sync also knows\n"
           "which revolution, from the cam.\n\n",
           f"{len(m['trigger_wheels'])} wheels.\n\n"]
    for w in m["trigger_wheels"]:
        s = slug(w["name"])
        (WHEELS / f"{s}.svg").write_text(wheel_svg(w))
        sync = "Phase (crank + cam)" if w.get("sync") == "PHASE" else "Crank"
        out.append(f"## {w['name']}\n\n")
        out.append(f"Sync: **{sync}**.")
        if "tdc_offset" in w:
            out.append(f" Library trigger offset: **{w['tdc_offset']:g}°**.")
        out.append("\n\n")
        for st in w["streams"]:
            out.append(f"- {describe(st)}\n")
        out.append(f"\n![{w['name']}: the teeth over one 720° cycle](../img/wheels/{s}.svg)\n\n")
    (REF / "trigger-wheels.md").write_text("".join(out))


# ---------------------------------------------------------------------------------------------------
# Appendix: the Proteus F7 board, from its board file
# ---------------------------------------------------------------------------------------------------
def gen_proteus():
    b = yaml.safe_load((ROOT / "definition" / "boards" / "proteus_f7.board.yaml").read_text())
    pins = {p.get("signal"): p for p in b.get("pins", []) if p.get("signal")}
    counts = {}
    # Counted from the CONNECTORS, so an on-board signal (AV12, the ECU's own supply) is not called an input.
    seen = set()
    for t in [t for c in b.get("connectors", []) for t in c.get("terminals", [])]:
        sig = t.get("signal") or ""
        if sig in seen or pins.get(sig, {}).get("assignable") is False:
            continue                                  # a +/- pair is one input; a fixed input is not one
        seen.add(sig)
        m = re.match(r"([A-Z]+)(\d+)$", sig)
        if m:
            counts[m.group(1)] = counts.get(m.group(1), 0) + 1
    out = ["<!-- GENERATED by manual/tools/gen_reference.py from definition/boards/proteus_f7.board.yaml — do not edit. -->\n\n",
           "# Appendix — Proteus F7 board\n\n",
           "The firmware also runs on the **Proteus F7**, an open-hardware ECU board with the same processor\n"
           "(STM32F767). Everything in this manual applies, with these differences:\n\n",
           f"- **Inputs and outputs** — {counts.get('IGN', 0)} ignition, {counts.get('LS', 0)} low-side, "
           f"{counts.get('HS', 0)} high-side outputs; {counts.get('AV', 0)} analogue voltage and "
           f"{counts.get('AT', 0)} temperature inputs; {counts.get('DIG', 0)} digital and "
           f"{counts.get('VR', 0)} VR inputs; two H-bridges; two CAN buses.\n",
           "- **No real-time clock**: the board uses the clock-crystal pins for other signals.\n"
           if not b.get("lse_hz") else "",
           "- **Its pin map is taken from the board's schematic and has not been tested on a running\n"
           "  engine.** Check every input and output on the bench (chapter 43) before trusting it.\n\n",
           "The chapters' pin names (AV1, LS5, IGN3 …) are the same; the connector positions are below.\n\n"]
    for c in b.get("connectors", []):
        out.append(f"## {c['id']} ({c.get('color', '')})\n\n{c.get('desc', '')}\n\n| Pin | Signal |\n|---|---|\n")
        for t in c.get("terminals", []):
            what = t.get("signal") or t.get("role", "")
            if t.get("line"):
                what += f" ({t['line']})"
            if pins.get(t.get("signal"), {}).get("assignable") is False:
                what += " — " + pins[t["signal"]].get("note", "fixed input")
            if t.get("role") == "power" and t.get("voltage"):
                what += f" {t['voltage']} V"
            out.append(f"| {t['pin']} | {cell(what)} |\n")
        out.append("\n")
    (REF / "proteus-f7.md").write_text("".join(out))


def main():
    m = load_meta()
    schema = yaml.safe_load(SCHEMA.read_text())
    gen_channels(m)
    gen_dtc(m)
    gen_sensor_types(schema)
    gen_output_templates(m)
    gen_lua(m)
    gen_wheels(m)
    gen_proteus()
    print(f"reference: {len(m['telemetry'])} channels, {len(m['dtc_descriptions'])} codes, "
          f"{len(schema['sensor_types'])} sensor types, {len(m['output_templates'])} templates, "
          f"{len(m['trigger_wheels'])} wheels -> manual/docs/reference")


if __name__ == "__main__":
    main()
