#pragma once

// PreferencesDialog — the Edit▸Preferences window. A WM-managed modal (own surface, title bar, draggable)
// with a left-nav + stacked-page layout: Units / Appearance / Connection / Editor /
// Logging. Live-apply (each control writes its setting immediately; a single Close button dismisses).
// The framework owns combo dropdowns, colour/font pickers, scroll/clip, and edge
// resize; the dialog only composes controls + flips options. Backends: Units→UnitManager,
// Appearance→JStyle, Connection→JSettings, Logging→JLog, Editor→EditorSettings. The Editor page has four
// sub-tabs — Surface, Tables (the Table type's schema form), Widget Defaults (a per-type form built from each
// widget class's JPropertyModel), and Panel Defaults (new-panel border/title style).

#include "../app/DesktopIntegration.h"   // the applications-menu question and its skip setting
#include <j/core/JWidget.h>
#include <j/core/JStyle.h>
#include <j/core/JTextHelper.h>
#include <j/core/JButton.h>
#include <j/core/JTitleBar.h>       // the ONE canonical styled title bar — no custom chrome
#include <j/core/JCloseButton.h>    // the ONE canonical window close control
#include <j/core/JCheckBox.h>
#include <j/core/MenuSystem.h>   // JMenuManager — the global tear-off switch
#include <j/core/JColorButton.h>
#include <j/core/JComboBox.h>
#include <j/core/JContainer.h>
#include <j/core/JFontButton.h>
#include <j/core/JLabel.h>
#include <j/core/JListView.h>
#include <j/core/JTabBar.h>
#include <j/core/JScrollArea.h>
#include <j/core/JKeySequenceEdit.h>   // key-capture rows on the Keyboard page
#include <j/core/JSpinBox.h>
#include <j/graphics/FontEngine.h>   // jReadFontFamilyName — show the current app-font family on the row
#include <j/graphics/GpuHal.h>
#include <j/graphics/RenderPrimitive.h>
#include <j/config/Settings.h>
#include <j/core/Log.h>
#include <j/io/SerialPort.h>            // the Serial port row lists what is actually plugged in

#include "../comms/DeviceScanner.h"     // and agrees with connect on what counts as a candidate
#include "WrapText.h"

#include <algorithm>
#include <cstdio>

#include <functional>

#if defined(_WIN32)
  #include <j/platforms/windows/WindowsPlatformWindow.h>
#else
  #include <j/platforms/linux/LinuxPlatformWindow.h>
#endif

#include "StudioVersion.h"             // STUDIO_VERSION, generated by CMake
#include "../model/DatalogRecorder.h"
#include "../model/EditorSettings.h"
#include "../model/Keymap.h"             // the global keyboard bindings shown on the Keyboard page
#include "../model/UnitManager.h"
#include "../surface/WidgetRegistry.h"   // catalog: widgetTypes/widgetTitle/widgetDefaultSize + makeWidgetInstance
#include "../surface/CanvasWidget.h"    // skin:: cascade
#include "../surface/CanvasWidget.h"       // prototype instance → its JPropertyModel (Widget Defaults form)
#include "../surface/PanelModel.h"         // prototype elements (one per widget type)
#include "../surface/PropertiesDock.h"     // the ONE inspector, reused as the Widget-Defaults detail pane
#include "../surface/widgets/TableWidget.h" // globalDefs(): what each "global" property falls back to
#include <j/core/JPropertyModel.h>
#include <j/core/FocusManager.h>

#include <memory>
#include <string>
#include <vector>

// TEAR-OFF MENUS DEFAULT OFF ON WINDOWS.
//
// Tearing a menu off promotes it to a floating top-level window, and that window is deliberately
// exempt from dismiss-on-outside — a torn-off menu is meant to stay put. It is closed by its own
// close button and nothing else. On Windows that is a window with no taskbar entry and no other way
// out, so a menu torn off by accident (a click that lands in the grab-strip) is stranded on screen
// until its close button is found. Off by default there; the preference below still turns it on.
inline constexpr bool kTearOffMenusDefault =
#if defined(_WIN32)
    false;
#else
    true;
#endif

class PreferencesDialog {
public:
    // Bigger than it was (540x430): the widest page is a form of label + control at a fixed left
    // column, and at the old width a sentence of explanation had nowhere to go but off the edge.
    static constexpr uint32_t kW = 720, kH = 560;
    // The size of the area a page is actually SHOWN in, installed by the app. The canvas presets are display
    // resolutions, and a page is never shown at display size: the docks, tabs and bars take their share. On a
    // fixed-size surface a canvas larger than this one does not scale down — it scrolls, so controls sit off
    // the right and below the fold. This is the number that makes a page fit, and only the app knows it.
    static inline std::function<std::pair<int,int>()> surfaceAreaFn;
    static constexpr float kNavW = 140.f, kNavRowH = 22.f, kBtnW = 84.f;
    static float kBtnH() { return jf::JStyle::current().buttonHeight; }   // HEIGHT from JStyle (single source of truth)
    // Metrics come from the active theme so the dialog stays consistent with the main window / other dialogs.
    static float hdrH() { return jf::JStyle::current().titleBarHeight; }   // title-bar height
    static float rowH() { return jf::JStyle::current().menuItemHeight; }   // control/row height
    static float padV() { return jf::JStyle::current().itemPadding; }      // form padding
    static float gapV() { return jf::JStyle::current().spacing; }          // inter-row gap
    // Desktop colour-scheme (GNOME's org.gnome.desktop.interface color-scheme). Defaults to dark if unknown.
    static bool osPrefersDark() {
        FILE* p = popen("gsettings get org.gnome.desktop.interface color-scheme 2>/dev/null", "r");
        if (!p) return true;
        char b[128] = { 0 }; if (!std::fgets(b, sizeof(b), p)) { /* empty */ } pclose(p);
        const std::string s(b);
        if (s.find("dark") != std::string::npos) return true;
        if (s.find("light") != std::string::npos || s.find("default") != std::string::npos) return false;
        return true;
    }

    // App-set hook: Appearance▸"Application Font" opens a font-file picker (main.cpp wires it to
    // win.setAppFont + persistence — the dialog has no window handle for the runtime atlas rebuild).
    static inline std::function<void()> onPickAppFont;
    // App-set hook: the ✕ on the Application Font row — clears the override (revert to the built-in default face).
    static inline std::function<void()> onClearAppFont;
    // Current app-font display name for the row's button ("Default" when unset). Reads the family from the
    // saved font-file path; the caller change-guards it so the file isn't re-read every frame.
    static std::string appFontLabel() {
        const std::string p = jf::JSettings::instance().get<std::string>("ui.font", "");
        if (p.empty()) return "Default";
        const std::string fam = jf::jReadFontFamilyName(p);
        return fam.empty() ? "Custom" : fam;
    }

    // App-set hook: Appearance▸Theme changed (0=Dark/app stylesheet, 1=Light, 2=System). main.cpp owns
    // the actual apply (it knows the stylesheet path) AND persists the choice so it survives a relaunch.
    static inline std::function<void(int)> onThemeChanged;
    // 0 = follow the screen's DPI; otherwise the multiplier the user picked. main.cpp applies it.
    static inline std::function<void(double)> onUiScaleChanged;
    // Appearance▸Docks changed (a per-host tab edge or enable toggle). The keys are written here; main.cpp
    // re-reads them and applies to the DockSpace it owns. One hook — the keys carry the detail.
    static inline std::function<void()> onDocksChanged;
    // Updates▸"Check now". main.cpp runs the check and reports the answer itself: the answer can arrive
    // after this dialog has closed, so the dialog must not be the thing that shows it.
    static inline std::function<void()> onCheckForUpdates;

#if defined(_WIN32)
    using PlatformWinType     = jf::JWindowsPlatformWindow;
    using NativeWinHandleType = HWND;
#else
    using PlatformWinType     = jf::JLinuxPlatformWindow;
    using NativeWinHandleType = xcb_window_t;
#endif

    static constexpr int kPageCount = 8;
    // "Datalog" records the ENGINE; "Diagnostics" is this program's own JLog output. They were one word
    // apart on the same rail, which is exactly how a user ends up setting the wrong one — the second
    // page was called "Logging" until the first one existed.
    static constexpr const char* kNav[kPageCount] = { "Units", "Appearance", "Connection", "Editor",
                                                      "Datalog", "Diagnostics", "Keyboard", "Updates" };
    static constexpr int kEditorTabCount = 5;
    static constexpr const char* kEditorTabs[kEditorTabCount] = { "Surface", "Tables", "Widget Defaults", "Panel Defaults", "Globals" };
    static constexpr float kSubTabH = 22.f;

    PreferencesDialog(jf::JGpuHal& hal, int screenX, int screenY, NativeWinHandleType parent)
        : m_window(std::make_unique<PlatformWinType>("Preferences", kW, kH, screenX, screenY,
                                                     jf::JPlatformWindowStyle::Borderless, parent))
        , m_surface(hal.createSurface(m_window->nativeHandle(), kW, kH)) {
        for (auto& p : m_pages) p = std::make_unique<jf::JContainer>(m_graph);
        buildUnits();
        buildAppearance();
        buildConnection();
        buildEditor();
        buildDatalog();
        buildDiagnostics();
        buildKeyboard();
        buildUpdates();
        buildWidgetDefaults();
        buildTables();
        buildPanelDefaults();
        buildGlobals();
        // Wrap each backed page in the framework's scroll area (it owns clip + scrollbar + wheel/drag). Give
        // the form its natural height so the scroll area knows the scrollable extent.
        for (int i : { 0, 1, 2, 3, 4, 5, 6, 7 }) {
            m_pageRaw[i] = m_pages[i].get();
            m_pages[i]->setBounds({ 0.f, 0.f, static_cast<float>(kW) - kNavW - 20.f, naturalH(i) });
            m_scrolls[i] = std::make_unique<jf::JScrollArea>(m_graph);
            m_scrolls[i]->addChildWidget(std::move(m_pages[i]));
        }
        // Set options and forget: the framework owns edge-resize (grab zones, cursors, WM handoff). The top
        // inset keeps our title-bar strip free for dragging/close.
        // Close is a REAL framework button, so it arms on press and fires on release-inside — press and
        // slide off to cancel, exactly like every other button. (It used to be a hand-drawn rect that
        // dismissed the dialog straight from the mouse-down, with no way to back out.) Being a widget it
        // also joins the tab order and activates on Space/Return.
        m_closeBtn = std::make_unique<jf::JButton>(m_graph, "Close", kBtnW, kBtnH());
        m_closeBtn->onClicked.connect([this] { m_done = true; });

        // The left rail and the Editor sub-tabs are REAL controls, not painted rectangles: they focus, take
        // Tab, and respond to the keyboard (arrows move a list selection / a tab). Previously both were
        // pushRectangle + an arithmetic hit-test (my/kNavRowH, mx/(width/4)), which is why the "tabs" could
        // never take focus.
        nav_ = std::make_unique<jf::JListView>(m_graph, std::vector<std::string>(kNav, kNav + kPageCount));
        nav_->setSelectedIndex(0);
        nav_->onSelectionChanged.connect([this](int i) { if (i >= 0 && i < kPageCount) m_page = i; });

        editorTabs_ = std::make_unique<jf::JTabBar>(m_graph,
                          std::vector<std::string>(kEditorTabs, kEditorTabs + kEditorTabCount));
        editorTabs_->onTabChanged.connect([this](int t) { if (t >= 0 && t < kEditorTabCount) m_editorTab = t; });

        m_window->setResizable(true);
        m_window->setResizeTopInset(hdrH());
        m_window->setMinSize(420, 320);
    }

    // This dialog's focus tree: the page on screen plus the controls the dialog owns directly. The
    // framework descends from these, so only what is actually in this dialog is a tab stop -- the page
    // visibility flags below then prune the rest of the subtree.
    void _refreshFocusRoots() {
        std::vector<jf::JWidget*> roots;
        for (int i = 0; i < kPageCount; ++i) if (m_scrolls[i]) roots.push_back(m_scrolls[i].get());
        if (m_tablesScroll) roots.push_back(m_tablesScroll.get());
        if (m_panelScroll)  roots.push_back(m_panelScroll.get());
        if (m_globalsScroll) roots.push_back(m_globalsScroll.get());
        if (m_typeList)     roots.push_back(m_typeList.get());
        if (m_wdefProps)    roots.push_back(m_wdefProps.get());
        if (nav_)           roots.push_back(nav_.get());
        if (editorTabs_ && m_page == 3) roots.push_back(editorTabs_.get());
        if (m_closeBtn)     roots.push_back(m_closeBtn.get());
        m_focus.setFocusRoots(std::move(roots));
    }

    void destroySurface(jf::JGpuHal& hal) { hal.destroySurface(m_surface); }

    bool pollAndRender(jf::JGpuHal& hal, jf::JPrimitiveBuffer& buf) {
        using namespace jf;
        if (m_done) return false;
        m_window->pollNativeEvents();
        if (m_window->shouldClose()) return false;
        if (!m_wdefPending.empty()) { showWidgetDefault(m_wdefPending); m_wdefPending.clear(); }   // safe (out of click handlers)
        if (m_appFontBtn) {   // reflect an Application-Font pick/clear that happened while this dialog is open
            const std::string p = JSettings::instance().get<std::string>("ui.font", "");
            if (p != m_appFontSeen) { m_appFontSeen = p; m_appFontBtn->setLabel(appFontLabel()); }
        }
        const float mx = m_window->mouseX(), my = m_window->mouseY();
        const bool pressed = m_window->consumePress(), released = m_window->consumeRelease(), held = m_window->isLeftButtonDown();

        // Click-to-focus, the framework's own (JAppWindow does the same for the main window): the widget
        // under the cursor takes focus before the press is dispatched, so every control focuses on click
        // without needing to ask for focus itself. Scoped to this dialog's graph.
        if (pressed) { _refreshFocusRoots(); jf::jRouteMouse(mx, my, m_focus); }

        // Live window size (the dialog is resizable — the WM drives interactive edge-resize below).
        const float W = static_cast<float>(m_window->width()), H = static_cast<float>(m_window->height());
        if (m_window->width() != m_lastW || m_window->height() != m_lastH) {
            hal.resizeSurface(m_surface, m_window->width(), m_window->height());   // follow the WM-driven resize
            m_lastW = m_window->width(); m_lastH = m_window->height();
        }
        // Title-bar drag (whole bar except the close button); the close ✕ dismisses. Edge/corner resize is
        // framework-managed (see setResizable() in the ctor).
        const jf::JRect closeR = jf::JCloseButton::rectFor({ 0.f, 0.f, W, hdrH() });
        // JCloseButton is a draw helper rather than a widget, so mirror the standard button contract by
        // hand: press ARMS, release INSIDE dismisses, release elsewhere cancels.
        if (pressed && jf::JCloseButton::hit(closeR, mx, my)) m_closeArmed = true;
        if (released) {
            const bool fire = m_closeArmed && jf::JCloseButton::hit(closeR, mx, my);
            m_closeArmed = false;
            if (fire) return false;
        }
        const bool inTitle = (my >= 0.f && my < hdrH() && mx < closeR.x);
        if (held && inTitle && !m_drag) { m_drag = true; m_ax = mx; m_ay = my; }
        if (m_drag) { auto [gx, gy] = m_window->globalCursorPos(); m_window->setPosition(gx - int(m_ax), gy - int(m_ay)); }
        if (!held) m_drag = false;

        // Keys go to the FOCUSED control first (typed digits into a spin box, Escape-restores-edit, …); an
        // unhandled Escape closes the dialog. m_focus is this dialog's own focus target while it's open.
        for (const auto& ke : m_window->consumeAllKeys()) {
            if (!ke.pressed) continue;
            // A key-capture row (Keyboard page) armed by a click swallows the next keystroke as its binding.
            // It doesn't take framework focus, so route to it explicitly before the focused-control path.
            bool captured = false;
            for (auto* e : m_keyEdits) if (e->capturing()) { e->handleKeyEvent(ke); captured = true; break; }
            if (captured) continue;
            // Standard framework routing: focused control first, then Tab / Shift-Tab traversal.
            // Scoped to this dialog's own scene graph so Tab can't walk into the window behind.
            if (jf::jRouteKey(ke, m_focus)) continue;
            if (ke.key == JKeyEvent::JKey::Escape) return false;
        }

        // Declare this window as the popup host for its own controls (live, so it tracks title-bar drags). The
        // framework opens + services combo dropdowns anchored here — the dialog does no popup work itself. When
        // a dropdown is open it grabs the pointer at the OS level, so the page below simply gets no clicks.
        m_graph.setHostWindow(m_window->screenX(), m_window->screenY(), static_cast<std::uintptr_t>(m_window->rawWindowId()));

        // Left rail: the list widget owns selection, hover and keyboard.
        if (nav_) {
            nav_->setBounds(navRect());
            nav_->handleMouseMove(mx, my);
            if (pressed)  nav_->handleMousePress(mx, my);
            if (released) nav_->handleMouseRelease(mx, my);
        }
        // Editor sub-tabs: the tab bar owns the active tab.
        if (editorTabs_ && m_page == 3) {
            const jf::JRect cr = contentRect();
            editorTabs_->setBounds({ cr.x, cr.y, cr.width, kSubTabH });
            editorTabs_->handleMouseMove(mx, my);
            if (pressed)  editorTabs_->handleMousePress(mx, my);
            if (released) editorTabs_->handleMouseRelease(mx, my);
        }

        // Only the page on screen is "visible". Every page is built up front and the inactive ones simply
        // aren't painted — but focus traversal and click hit-testing go by isVisible(), so without this the
        // tab ring spans all six pages and Tab walks onto controls you cannot see. Hiding the page's scroll
        // area is enough: JWidget visibility is effective, so its whole subtree drops out with it.
        for (int i = 0; i < kPageCount; ++i)
            if (m_scrolls[i]) m_scrolls[i]->setVisible(i == m_page);
        // Editor page (3) hosts several sub-panels selected by its own tab bar.
        if (m_tablesScroll) m_tablesScroll->setVisible(m_page == 3 && m_editorTab == 1);
        if (m_panelScroll)  m_panelScroll->setVisible (m_page == 3 && m_editorTab == 3);
        if (m_typeList)     m_typeList->setVisible    (m_page == 3 && m_editorTab == 2);
        if (m_wdefProps)    m_wdefProps->setVisible   (m_page == 3 && m_editorTab == 2);
        if (m_globalsScroll) m_globalsScroll->setVisible(m_page == 3 && m_editorTab == 4);
        if (m_scrolls[3])   m_scrolls[3]->setVisible  (m_page == 3 && m_editorTab == 0);

        // Initial focus: a freshly-opened window focuses its first control, like any toolkit — so the
        // keyboard works immediately instead of only after the user clicks something. Done once, after
        // page visibility is settled so the order holds only the controls actually on screen.
        _refreshFocusRoots();
        if (!m_focusSeeded) { m_focusSeeded = true; m_focus.focusFirst(); }

        // Route input to the active page. The framework's JScrollArea owns each viewport (layout, clip, wheel/
        // drag scroll, scrollbar) — no offsets/clip in the app. The Editor page adds a sub-tab bar.
        auto feedScroll = [&](JScrollArea* sa, const JRect& r) {
            sa->setBounds(r);
            sa->handleMouseMove(mx, my);
            if (pressed)  sa->handleMousePress(mx, my);
            if (released) sa->handleMouseRelease(mx, my);
            if (const float wheel = m_window->consumeWheel(); wheel != 0.f) sa->handleScroll(mx, my, wheel);
        };
        if (m_page == 3) {
            const JRect cr = contentRect();
            if (pressed && my >= cr.y && my < cr.y + kSubTabH) {   // sub-tab bar click
                const float tw = cr.width / kEditorTabCount;
                const int t = static_cast<int>((mx - cr.x) / tw);
                if (t >= 0 && t < kEditorTabCount) m_editorTab = t;
            }
            const JRect sr = editorSubRect();
            if (m_editorTab == 0 && m_scrolls[3]) { feedScroll(m_scrolls[3].get(), sr); }
            else if (m_editorTab == 1 && m_tablesScroll) { feedScroll(m_tablesScroll.get(), sr); }
            else if (m_editorTab == 3 && m_panelScroll)  { feedScroll(m_panelScroll.get(), sr); }
            else if (m_editorTab == 4 && m_globalsScroll) { feedScroll(m_globalsScroll.get(), sr); }
            else if (m_editorTab == 2 && m_typeList && m_wdefProps) {   // Widget Defaults: master list + inspector detail
                const float listW = 170.f;
                m_typeList->setBounds({ sr.x, sr.y, listW, sr.height });
                m_typeList->handleMouseMove(mx, my);
                if (pressed)  m_typeList->handleMousePress(mx, my);
                if (released) m_typeList->handleMouseRelease(mx, my);
                m_wdefProps->setBounds({ sr.x + listW + 6.f, sr.y, sr.width - listW - 6.f, sr.height });
                m_wdefProps->handleMouseMove(mx, my);
                if (pressed)  m_wdefProps->handleMousePress(mx, my);
                if (released) m_wdefProps->handleMouseRelease(mx, my);
                // The wheel goes to whichever of the two panes the cursor is over. It used to be handed to
                // the inspector unconditionally, so the type LIST — which has its own scrollbar and is the
                // pane you scroll to find a widget — ignored the wheel entirely, and scrolling over it
                // moved the panel beside it instead.
                if (const float wheel = m_window->consumeWheel(); wheel != 0.f) {
                    const bool overList = mx < sr.x + listW;
                    if (overList) m_typeList->handleScroll(mx, my, wheel);
                    else          m_wdefProps->handleScroll(mx, my, wheel);
                }
            }
        } else if (JScrollArea* sa = m_scrolls[m_page].get()) {
            feedScroll(sa, contentRect());
        }
        _fitNotes();

        const float btnY = H - kBtnH() - 12.f, closeX = W - kBtnW - 12.f;
        if (m_closeBtn) {
            m_closeBtn->setBounds({ closeX, btnY, kBtnW, kBtnH() });
            m_closeBtn->handleMouseMove(mx, my);
            if (pressed)  m_closeBtn->handleMousePress(mx, my);
            if (released) m_closeBtn->handleMouseRelease(mx, my);   // onClicked -> m_done, only if released inside
            if (m_done) return false;
        }

        buf.clear();
        _render(buf, mx, my, btnY, closeX);
        auto frame = hal.beginFrame(m_surface);
        hal.drawPrimitives(buf);
        hal.submitAndPresentFrame(frame);
        return true;
    }

private:
    // ---- page builders -------------------------------------------------------------------------------
    // Content viewport (right of the nav, above the footer) + a page's natural form height / scroll extent.
    // The nav rail fills the left column below the title bar. JListView sizes its rows itself
    // (lineHeight + 8, plus padding), so pinning the height to kPageCount * kNavRowH clipped the last
    // entry -- let it own the whole rail instead.
    jf::JRect navRect() const {
        const float H = static_cast<float>(m_window->height());
        return { 0.f, hdrH() + 6.f, kNavW, std::max(0.f, H - hdrH() - 12.f) };
    }

    jf::JRect contentRect() const {
        const float W = static_cast<float>(m_window->width()), H = static_cast<float>(m_window->height());
        return { kNavW, hdrH() + 6.f, W - kNavW, H - hdrH() - kBtnH() - 30.f };
    }
    // The Editor page's sub-content area (below its sub-tab bar).
    jf::JRect editorSubRect() const {
        jf::JRect cr = contentRect();
        return { cr.x, cr.y + kSubTabH + 2.f, cr.width, cr.height - kSubTabH - 2.f };
    }
    float naturalH(int page) const {
        // Generous: each row at rowH+gap, plus slack for the taller Flex button row + padding, so the scroll
        // area's extent always covers the real content (never clips the last rows).
        const int r = m_rows[page];
        float h = padV() * 2.f + (r + 2) * (rowH() + gapV()) + rowH();
        for (const auto& [pg, n] : m_notes)   // a wrapped note is as many rows tall as its text makes it
            if (pg == page) h += std::max(0.f, n->bounds().height - rowH());
        return h;
    }

    // A NOTE WRAPS, and its row is as tall as the wrapped text. It is sized at `w` up front, then refit
    // to the width the form actually gives it (_fitNotes), and the page's scroll extent follows.
    jf::JLabel* addNote(jf::JContainer* f, int page, const std::string& text, float w = 330.f) {
        auto u = std::make_unique<jf::JLabel>(m_graph, text, w);
        u->setWordWrap(true);
        jf::JLabel* l = f->add(std::move(u));
        l->setBounds({ 0.f, 0.f, w, std::max(rowH(), l->heightFor(w)) });
        m_notes.emplace_back(page, l);
        return l;
    }
    void _fitNotes() {
        bool changed = false;
        for (const auto& [pg, n] : m_notes)
            if (pg == m_page) changed |= wraptext::fit(n);
        if (changed && m_pageRaw[m_page]) {
            jf::JRect b = m_pageRaw[m_page]->bounds();
            b.height = naturalH(m_page);
            m_pageRaw[m_page]->setBounds(b);
        }
    }

    void buildUnits() {
        using namespace jf;
        JContainer* f = m_pages[0].get();
        f->setLayoutMode(JLayoutMode::Form)->setGap(gapV())->setPadding(JEdges{ padV(), padV(), padV(), padV() });

        // Metric / Imperial default buttons.
        auto hbox = std::make_unique<JContainer>(m_graph);
        hbox->setLayoutMode(JLayoutMode::Flex)->setGap(gapV());
        JButton* metric   = hbox->add(std::make_unique<JButton>(m_graph, "Metric",   90.f));
        JButton* imperial = hbox->add(std::make_unique<JButton>(m_graph, "Imperial", 90.f));
        metric->onClicked.connect([this]   { UnitManager::instance().applySystemDefaults(UnitManager::UnitSystem::Metric);   refreshUnitCombos(); });
        imperial->onClicked.connect([this] { UnitManager::instance().applySystemDefaults(UnitManager::UnitSystem::Imperial); refreshUnitCombos(); });
        f->add(std::make_unique<JLabel>(m_graph, "Set defaults:", 150.f)); f->add(std::move(hbox));

        // One preferred-unit combo per quantity.
        for (const std::string& qid : UnitManager::instance().quantities()) {
            const UnitManager::Quantity q = UnitManager::instance().getQuantity(qid);
            std::vector<std::string> labels, ids;
            for (const auto& u : q.units) { labels.push_back(u.label); ids.push_back(u.id); }
            f->add(std::make_unique<JLabel>(m_graph, q.label + ":", 150.f));
            JComboBox* combo = f->add(std::make_unique<JComboBox>(m_graph, labels));
            selectUnit(combo, ids, UnitManager::instance().preferredUnit(qid));
            combo->onIndexChanged.connect([qid, ids](int i) {
                if (i >= 0 && i < static_cast<int>(ids.size())) UnitManager::instance().setPreferredUnit(qid, ids[i]);
            });
            m_unitRows.push_back({ combo, ids, qid });
        }
        m_rows[0] = 1 + static_cast<int>(m_unitRows.size());   // "Set defaults" + one per quantity
    }

    void buildConnection() {
        using namespace jf;
        JContainer* f = m_pages[2].get();
        f->setLayoutMode(JLayoutMode::Form)->setGap(gapV())->setPadding(JEdges{ padV(), padV(), padV(), padV() });
        auto& s = JSettings::instance();
        // WHICH PORT. Automatic is right whenever the studio can tell which device is an ECU — it
        // prefers the jayecu CDC descriptor and, when several answer, asks. But it cannot always tell:
        // a port with no usable descriptor is indistinguishable from any other, and the studio then
        // picks one and opens it. Naming the port ends the guessing, and it is also the only way to
        // say "that one" when two ECUs are on the bench and both are the same hardware.
        //
        // The list is read when the dialog opens, so plugging an ECU in and reopening this page shows
        // it. A remembered port that is not present right now is kept in the list and marked, rather
        // than silently dropped — forgetting the choice because the ECU is unplugged is how a setting
        // becomes something you have to set twice.
        f->add(std::make_unique<JLabel>(m_graph, "Serial port", 240.f));
        m_portIds.clear();
        std::vector<std::string> portLabels{ "Automatic" };
        m_portIds.push_back("");
        const std::string savedPort = s.get<std::string>("connection.port", std::string());
        bool savedSeen = false;
        for (const auto& info : jf::JSerialPort::availablePorts()) {
            if (!DeviceScanner::isUsbSerial(info)) continue;
            std::string label = info.port;
            if (info.hasVidPid) {
                char ids[16];
                std::snprintf(ids, sizeof ids, "%04x:%04x", info.vendorId, info.productId);
                label += "  (" + std::string(ids);
                if (info.vendorId == 0x0483 && info.productId == 0x5740) label += ", jayecu";
                label += ")";
            } else if (!info.description.empty() && info.description != info.port) {
                label += "  (" + info.description + ")";
            }
            portLabels.push_back(label);
            m_portIds.push_back(info.port);
            if (info.port == savedPort) savedSeen = true;
        }
        if (!savedPort.empty() && !savedSeen) {           // remembered, but not plugged in at the moment
            portLabels.push_back(savedPort + "  (not connected)");
            m_portIds.push_back(savedPort);
        }
        JComboBox* port = f->add(std::make_unique<JComboBox>(m_graph, portLabels));
        for (size_t i = 0; i < m_portIds.size(); ++i)
            if (m_portIds[i] == savedPort) { port->setCurrentIndex(static_cast<int>(i)); break; }
        port->onIndexChanged.connect([this](int i) {
            const std::string sel = (i >= 0 && i < static_cast<int>(m_portIds.size())) ? m_portIds[size_t(i)]
                                                                                       : std::string();
            JSettings::instance().set("connection.port", JVariant(sel));
        });

        f->add(std::make_unique<JLabel>(m_graph, "Reopen last project on launch", 240.f));
        JCheckBox* reopen = f->add(std::make_unique<JCheckBox>(m_graph, "", 30.f));
        reopen->setChecked(s.get<bool>("startup.reopenLastProject", false));
        reopen->onStateChanged.connect([](bool on) { JSettings::instance().set("startup.reopenLastProject", on); });
        f->add(std::make_unique<JLabel>(m_graph, "Connect automatically on launch", 240.f));
        JCheckBox* autoc = f->add(std::make_unique<JCheckBox>(m_graph, "", 30.f));
        autoc->setChecked(s.get<bool>("connection.autoConnect", false));
        autoc->onStateChanged.connect([](bool on) { JSettings::instance().set("connection.autoConnect", on); });
        // WHICH protocol the connect button probes with. Off, it follows the loaded schema: a definition
        // imported from a .ini carries a tsProtocol block and gets the TunerStudio handshake, anything else
        // gets the native identity request. That is fine until the studio comes up on the built-in schema
        // with a rusEFI ECU on the bench, where the native request is answered with silence and the button
        // reports "ECU did not identify". On, the signature query goes first regardless, and the definition
        // matching whatever answers is loaded from the imported library.
        f->add(std::make_unique<JLabel>(m_graph, "Probe with rusEFI / TunerStudio protocol", 240.f));
        JCheckBox* tsProbe = f->add(std::make_unique<JCheckBox>(m_graph, "", 30.f));
        tsProbe->setChecked(s.get<bool>("connection.rusefiProbe", false));
        tsProbe->onStateChanged.connect([](bool on) { JSettings::instance().set("connection.rusefiProbe", on); });

        // Engine-cycle recorder depth. How much history is worth holding depends on what is being
        // chased: a drifting spark shows up in a handful of cycles, an intermittent misfire needs a
        // long tail. Each frame is one captured cycle held in the studio, so this is memory, not
        // load on the ECU — the ECU still records exactly one cycle per request either way.
        f->add(std::make_unique<JLabel>(m_graph, "Engine cycle frames to keep", 240.f));
        JComboBox* frames = f->add(std::make_unique<JComboBox>(
            m_graph, std::vector<std::string>{ "20", "60", "120", "300" }));
        const int cur = s.get<int>("engineCycle.frames", 60);
        frames->setCurrentIndex(cur <= 20 ? 0 : cur <= 60 ? 1 : cur <= 120 ? 2 : 3);
        frames->onIndexChanged.connect([](int i) {
            static const int kFrames[] = { 20, 60, 120, 300 };
            JSettings::instance().set("engineCycle.frames", kFrames[i < 0 ? 1 : (i > 3 ? 3 : i)]);
        });
        m_rows[2] = 5;
    }

    void buildAppearance() {
        using namespace jf;
        JContainer* f = m_pages[1].get();
        f->setLayoutMode(JLayoutMode::Form)->setGap(gapV())->setPadding(JEdges{ padV(), padV(), padV(), padV() });
        // INTERFACE SCALE — how big the whole interface is, as one number. Screens are not the same size:
        // a 30 px control that reads well on a 1080p laptop is a smudge on a 4K panel. This re-measures
        // the style and rebuilds the font at the same scale, so text and the boxes around it grow
        // together and the layout reflows around them. It is not a zoom: nothing is magnified, so text
        // stays crisp and a wider window still buys more content rather than bigger content.
        f->add(std::make_unique<JLabel>(m_graph, "Interface scale", 150.f));
        {
            static const std::vector<std::pair<const char*, double>> kScales{
                { "Auto (screen DPI)", 0.0 }, { "100 %", 1.0 }, { "125 %", 1.25 },
                { "150 %", 1.5 }, { "175 %", 1.75 }, { "200 %", 2.0 } };
            std::vector<std::string> names;
            for (const auto& [n, v] : kScales) names.emplace_back(n);
            JComboBox* sc = f->add(std::make_unique<JComboBox>(m_graph, names));
            const double cur = JSettings::instance().get<double>("ui.scale", 0.0);
            int idx = 0;
            for (size_t i = 0; i < kScales.size(); ++i) if (kScales[i].second == cur) { idx = int(i); break; }
            sc->setCurrentIndex(idx);   // seed BEFORE wiring, so opening the page applies nothing
            sc->onIndexChanged.connect([](int i) {
                if (i < 0 || i >= int(kScales.size())) return;
                JSettings::instance().set("ui.scale", kScales[size_t(i)].second);
                if (onUiScaleChanged) onUiScaleChanged(kScales[size_t(i)].second);
            });
        }
        f->add(std::make_unique<JLabel>(m_graph, "Theme", 150.f));
        JComboBox* theme = f->add(std::make_unique<JComboBox>(m_graph, std::vector<std::string>{ "Dark", "Light", "System (follow OS)" }));
        theme->setCurrentIndex(JSettings::instance().get<int>("appearance.theme", 0));   // seed BEFORE wiring (no spurious apply)
        theme->onIndexChanged.connect([](int i){ if (onThemeChanged) onThemeChanged(i); });   // main.cpp applies + persists
        // Application Font: a button showing the CURRENT font + an ✕ to clear (revert to Default), mirroring
        // the other font prefs. The label refreshes from settings while open, so a pick/clear shows at once.
        auto fontRow = std::make_unique<JContainer>(m_graph);
        fontRow->setLayoutMode(JLayoutMode::Flex)->setDirection(JFlexDirection::JRow)->setGap(gapV());   // [Default][x] side by side (Flex defaults to Column)
        m_appFontBtn = fontRow->add(std::make_unique<JButton>(m_graph, appFontLabel(), 140.f));
        m_appFontBtn->onClicked.connect([]{ if (onPickAppFont) onPickAppFont(); });
        JButton* clearFont = fontRow->add(std::make_unique<JButton>(m_graph, "x", 24.f));
        clearFont->onClicked.connect([]{ if (onClearAppFont) onClearAppFont(); });
        m_appFontSeen = JSettings::instance().get<std::string>("ui.font", "");
        f->add(std::make_unique<JLabel>(m_graph, "Application Font", 150.f)); f->add(std::move(fontRow));
        auto colorRow = [&](const char* lab, uint8_t* target) {
            f->add(std::make_unique<JLabel>(m_graph, lab, 150.f));
            JColorButton* cb = f->add(std::make_unique<JColorButton>(m_graph, 170.f));
            char hx[8]; std::snprintf(hx, sizeof(hx), "#%02x%02x%02x", target[0], target[1], target[2]);
            cb->setColorHex(hx);
            cb->onColorChanged.connect([target](const std::string& h){ uint8_t o[4]; if (skin::parseHex(h, o)) { target[0]=o[0]; target[1]=o[1]; target[2]=o[2]; } });
        };
        colorRow("Background", JStyle::current().Surface0);
        colorRow("Text",       JStyle::current().TextPrimary);
        colorRow("Accent",     JStyle::current().Accent);
        colorRow("Border",     JStyle::current().Border);
        // Default decimals (0..4). Stored, not consumed: value controls format via their own
        // per-control "format" prop. The Application Font row above it is omitted — the single-font
        // atlas makes it a no-op (same limit as label bold/rotation), so a Font picker here would be a dead control.
        f->add(std::make_unique<JLabel>(m_graph, "Default decimals", 150.f));
        JSpinBox* dec = f->add(std::make_unique<JSpinBox>(m_graph, 0, 4, 100.f));
        dec->setValue(EditorSettings::instance().defaultDecimals());
        dec->onValueChanged.connect([](int d){ EditorSettings::instance().setDefaultDecimals(d); });
        // Tear-off menus: the grab-strip that promotes a menu to a floating window. Off, the global switch
        // suppresses it for every menu. Applied live and re-applied at startup (main.cpp).
        f->add(std::make_unique<JLabel>(m_graph, "Tear-off menus", 150.f));
        JCheckBox* tearoff = f->add(std::make_unique<JCheckBox>(m_graph, "", 30.f));
        tearoff->setChecked(JSettings::instance().get<bool>("ui.tearOffMenus", kTearOffMenusDefault));
        tearoff->onStateChanged.connect([](bool on){
            JSettings::instance().set("ui.tearOffMenus", on);
            JMenuManager::instance().setTearOffEnabled(on);
        });
        // Per-dock-host row: an Enabled checkbox (off collapses the whole area) + the tab-strip edge.
        // Defaults keep the current look — the side docks' tabs face the centre, the bottom's sit on top.
        auto dockRow = [&](const char* label, const char* enKey, const char* edgeKey, int defEdge) {
            auto row = std::make_unique<JContainer>(m_graph);
            row->setLayoutMode(JLayoutMode::Flex)->setDirection(JFlexDirection::JRow)->setGap(gapV());
            JCheckBox* en = row->add(std::make_unique<JCheckBox>(m_graph, "", 30.f));
            en->setChecked(JSettings::instance().get<bool>(enKey, true));
            en->onStateChanged.connect([enKey](bool on){ JSettings::instance().set(enKey, on); if (onDocksChanged) onDocksChanged(); });
            JComboBox* edge = row->add(std::make_unique<JComboBox>(m_graph, std::vector<std::string>{ "Top", "Bottom", "Left", "Right" }));
            edge->setCurrentIndex(JSettings::instance().get<int>(edgeKey, defEdge));
            edge->onIndexChanged.connect([edgeKey](int i){ JSettings::instance().set(edgeKey, i); if (onDocksChanged) onDocksChanged(); });
            f->add(std::make_unique<JLabel>(m_graph, label, 150.f));
            f->add(std::move(row));
        };
        dockRow("Left dock",   "dock.leftEnabled",   "ui.dockEdge.left",   3);   // tabs on the Right edge (inward)
        dockRow("Right dock",  "dock.rightEnabled",  "ui.dockEdge.right",  2);   // tabs on the Left edge (inward)
        dockRow("Bottom dock", "dock.bottomEnabled", "ui.dockEdge.bottom", 0);   // tabs on Top
        m_rows[1] = 11;
    }

    // Diagnostics — this program's own log output (JLog / genesis.log), for whoever is debugging the
    // studio. Nothing here touches a datalog; see buildDatalog().
    void buildDiagnostics() {
        using namespace jf;
        JContainer* f = m_pages[5].get();
        f->setLayoutMode(JLayoutMode::Form)->setGap(gapV())->setPadding(JEdges{ padV(), padV(), padV(), padV() });
        f->add(std::make_unique<JLabel>(m_graph, "Minimum level", 150.f));
        JComboBox* lvl = f->add(std::make_unique<JComboBox>(m_graph, std::vector<std::string>{ "Trace", "Debug", "Info", "Warn", "Error", "Off" }));
        lvl->setCurrentIndex(std::clamp(static_cast<int>(JLog::instance().globalLevel()), 0, 5));
        lvl->onIndexChanged.connect([](int i){ JLog::instance().setGlobalLevel(static_cast<JLogLevel>(i)); });
        m_rows[5] = 1;
    }

    // Datalog — recording what the ECU is STREAMING, for the person tuning the engine. The other half
    // of this feature lives on the ECU (its own gate, its own card, its own retention); everything here
    // is about the studio's recordings and its own directory, and confusing the two would be a good way
    // to delete the wrong files.
    void buildDatalog() {
        using namespace jf;
        JContainer* f = m_pages[4].get();
        f->setLayoutMode(JLayoutMode::Form)->setGap(gapV())->setPadding(JEdges{ padV(), padV(), padV(), padV() });

            // WHAT STAYS HERE is what belongs to the STUDIO: where its own recordings go, whether it
        // starts one per session, and how many it keeps. Everything about WHICH CHANNELS moved to the
        // Logging menu — that set is written to the TUNE, and a tune field has no business being
        // edited from an application-preferences page.
        f->add(std::make_unique<JLabel>(m_graph, "Record every session", 150.f));
        JCheckBox* autoRec = f->add(std::make_unique<JCheckBox>(m_graph, ""));
        autoRec->setChecked(DatalogRecorder::autoLog());
        autoRec->setTooltip("Start recording when the ECU connects and stop when it disconnects. The "
                            "Record button still overrides it either way: stopping ends that log, and "
                            "starting begins a new one.");
        autoRec->onStateChanged.connect([](bool on){ DatalogRecorder::setAutoLog(on); });

        // 0 = keep everything, and it is the default. Deleting a tuner's data is not something to start
        // doing because nobody chose otherwise.
        f->add(std::make_unique<JLabel>(m_graph, "Keep recent logs", 150.f));
        JSpinBox* keep = f->add(std::make_unique<JSpinBox>(m_graph, 0, 999, 90.f));
        keep->setValue(DatalogRecorder::keepFiles());
        keep->setTooltip("How many recordings to keep in the folder below; 0 keeps everything. Older "
                         "files are removed when a recording ENDS \xE2\x80\x94 never while one is open, and "
                         "never the one just written.");
        keep->onValueChanged.connect([](int n){ DatalogRecorder::setKeepFiles(n); });

        f->add(std::make_unique<JLabel>(m_graph, "Folder", 150.f));
        JLineEdit* dir = f->add(std::make_unique<JLineEdit>(m_graph, DatalogRecorder::resolvedDirectory()));
        dir->setTooltip("Where recordings are written. Leave it as it is for the default under the "
                        "studio's data folder.");
        dir->onTextChanged.connect([](const std::string& t){ DatalogRecorder::setDirectory(t); });

        // WHAT IT COSTS, said before it is a surprise. Every telemetry channel is a column, and at 30 Hz
        // that is around a hundred megabytes an hour — the kind of number better read here than found
        // later on a full disk.
        f->add(std::make_unique<JLabel>(m_graph, "", 150.f));
        // WRAPPED, as tall as its text. It was one clipped line ending in "Abo".
        m_datalogCost = addNote(f, 4, "", 420.f);
        refreshDatalogCost();

        m_rows[4] = 6;
    }

    // WHAT IT COSTS, in this definition's own numbers rather than a rule of thumb: the channel count is
    // known, a column averages about two bytes of text, and the rate is the one the link delivers. Said
    // here because a full disk is a worse place to learn it.
    // WHAT A RECORDING COSTS, in this definition's own numbers rather than a rule of thumb. Said here
    // because a full disk is a worse place to learn it; WHICH channels is the Logging menu's business.
    void refreshDatalogCost() {
        if (!m_datalogCost) return;
        const size_t n = DatalogRecorder::recordingChannels().size();
        const double mbPerHour = (n * 2.0 + 8.0) * 30.0 * 3600.0 / (1024.0 * 1024.0);
        char buf[240];
        std::snprintf(buf, sizeof buf,
                      "Recording %zu channels \xE2\x80\x94 about %.0f MB an hour at 30 Hz. Channels are chosen "
                      "on the Logging menu. Files are MSL, which MegaLogViewer opens directly.", n, mbPerHour);
        m_datalogCost->setText(buf);
    }

    // Keyboard shortcuts — one capture row per rebindable Keymap action, grouped (Value / Table / Surface)
    // with a header row before each group. Clicking a box arms it (JKeySequenceEdit); the next keystroke is
    // captured and written straight to the global Keymap (which persists via JSettings). This is the same
    // capture control the standalone Table Key Bindings dialog uses, hosted inline here.
    void buildKeyboard() {
        using namespace jf;
        JContainer* f = m_pages[6].get();
        f->setLayoutMode(JLayoutMode::Form)->setGap(gapV())->setPadding(JEdges{ padV(), padV(), padV(), padV() });
        int rows = 0;
        bool first = true; Keymap::Group cur{};
        for (Keymap::Action a : Keymap::allActions()) {
            const Keymap::Group g = Keymap::groupOf(a);
            if (first || g != cur) {                          // section header row (kept as a label pair so Form pairing holds)
                cur = g; first = false;
                f->add(std::make_unique<JLabel>(m_graph, Keymap::groupLabel(g), 150.f)); f->add(std::make_unique<JLabel>(m_graph, "", 150.f));
                rows++;
            }
            f->add(std::make_unique<JLabel>(m_graph, Keymap::label(a), 150.f));
            JKeySequenceEdit* e = f->add(std::make_unique<JKeySequenceEdit>(m_graph, Keymap::toString(Keymap::instance().binding(a)), 150.f));
            e->onClicked.connect([this, e] { for (auto* o : m_keyEdits) if (o != e) o->setCapturing(false); });   // single-arm
            e->onCaptured.connect([a, e](const JKeyEvent& ke) {
                const Keymap::KeySpec spec = Keymap::fromEvent(ke);
                Keymap::instance().setBinding(a, spec);
                e->setText(Keymap::toString(spec));
            });
            m_keyEdits.push_back(e);
            rows++;
        }
        m_rows[6] = rows;
    }

    // Updates — the studio's own updates, and ECU firmware (firmware + meta + dashboard, released on its
    // own). Checking online and telling you about the ECU are separate switches: the second needs no
    // network, so it still works at a track with the first turned off.
    void buildUpdates() {
        using namespace jf;
        JContainer* f = m_pages[7].get();
        f->setLayoutMode(JLayoutMode::Form)->setGap(gapV())->setPadding(JEdges{ padV(), padV(), padV(), padV() });
        f->add(std::make_unique<JLabel>(m_graph, "This version", 240.f));
        f->add(std::make_unique<JLabel>(m_graph, STUDIO_VERSION, 150.f));

        f->add(std::make_unique<JLabel>(m_graph, "Check for studio updates at startup", 240.f));
        JCheckBox* onStart = f->add(std::make_unique<JCheckBox>(m_graph, "", 30.f));
        onStart->setChecked(JSettings::instance().get<bool>("updates.checkOnStartup", true));
        onStart->onStateChanged.connect([](bool on) { JSettings::instance().set("updates.checkOnStartup", on); });

        f->add(std::make_unique<JLabel>(m_graph, "Check for firmware updates at startup", 240.f));
        JCheckBox* fwStart = f->add(std::make_unique<JCheckBox>(m_graph, "", 30.f));
        fwStart->setChecked(JSettings::instance().get<bool>("updates.firmwareOnStartup", true));
        fwStart->onStateChanged.connect([](bool on) { JSettings::instance().set("updates.firmwareOnStartup", on); });

        f->add(std::make_unique<JLabel>(m_graph, "Tell me when a connected ECU has older firmware", 240.f));
        JCheckBox* fwConn = f->add(std::make_unique<JCheckBox>(m_graph, "", 30.f));
        fwConn->setChecked(JSettings::instance().get<bool>("updates.firmwareOnConnect", true));
        fwConn->onStateChanged.connect([](bool on) { JSettings::instance().set("updates.firmwareOnConnect", on); });

        // THE BETA CHANNEL. Off, only full firmware releases are fetched; on, pre-releases too, and the
        // newest wins. Betas are published between releases for people testing new firmware.
        f->add(std::make_unique<JLabel>(m_graph, "Include beta firmware", 240.f));
        JCheckBox* fwBeta = f->add(std::make_unique<JCheckBox>(m_graph, "", 30.f));
        fwBeta->setChecked(JSettings::instance().get<bool>("updates.firmwareBeta", false));
        fwBeta->onStateChanged.connect([](bool on) { JSettings::instance().set("updates.firmwareBeta", on); });

        // THE APPLICATIONS-MENU QUESTION (Linux AppImage; app/DesktopIntegration.h). Ticked when the user
        // declined it at startup, so they are not asked every launch; untick to be asked again next time.
        int menuRows = 0;
#if !defined(_WIN32)
        f->add(std::make_unique<JLabel>(m_graph, "Skip the applications menu check", 240.f));
        JCheckBox* skipMenu = f->add(std::make_unique<JCheckBox>(m_graph, "", 30.f));
        skipMenu->setChecked(JSettings::instance().get<bool>(desktop::kSkipSetting, false));
        skipMenu->onStateChanged.connect([](bool on) { JSettings::instance().set(desktop::kSkipSetting, on); });
        menuRows = 1;
#endif

        f->add(std::make_unique<JLabel>(m_graph, "", 240.f));
        JButton* now = f->add(std::make_unique<JButton>(m_graph, "Check now", 110.f));
        now->onClicked.connect([] { if (onCheckForUpdates) onCheckForUpdates(); });

        f->add(std::make_unique<JLabel>(m_graph, "", 240.f));
        addNote(f, 7, "Checks online for a newer studio and newer ECU firmware. Firmware is downloaded "
                      "and kept, but never put on an ECU without asking. Beta firmware is for testing: "
                      "leave it off on a car you depend on.");
        m_rows[7] = 8 + menuRows;
    }

    void buildEditor() {
        using namespace jf;
        JContainer* f = m_pages[3].get();
        f->setLayoutMode(JLayoutMode::Form)->setGap(gapV())->setPadding(JEdges{ padV(), padV(), padV(), padV() });
        EditorSettings& es = EditorSettings::instance();
        auto gridU = std::make_unique<JSpinBox>(m_graph, 2, 200, 100.f); JSpinBox* grid = gridU.get(); grid->setValue(es.gridSize());
        grid->onValueChanged.connect([](int v) { EditorSettings::instance().setGridSize(v); });
        auto showU = std::make_unique<JCheckBox>(m_graph, "", 30.f); JCheckBox* show = showU.get(); show->setChecked(es.showGrid());
        show->onStateChanged.connect([](bool on) { EditorSettings::instance().setShowGrid(on); });
        auto snapGU = std::make_unique<JCheckBox>(m_graph, "", 30.f); JCheckBox* snapG = snapGU.get(); snapG->setChecked(es.snapToGrid());
        snapG->onStateChanged.connect([](bool on) { EditorSettings::instance().setSnapToGrid(on); });
        auto snapWU = std::make_unique<JCheckBox>(m_graph, "", 30.f); JCheckBox* snapW = snapWU.get(); snapW->setChecked(es.snapToNeighbours());
        snapW->onStateChanged.connect([](bool on) { EditorSettings::instance().setSnapToNeighbours(on); });
        // WHAT THIS ACTUALLY CHOOSES, now that Interface scale exists: whether a page is rendered at the
        // interface scale (and scrolls when it does not fit) or squeezed to fit the window. It used to be
        // labelled "Static surface size", which said nothing about either, and it used to be a second
        // scale control fighting the first. Shown inverted, because "fit to the window" is the thing a
        // reader can picture; the setting it stores is still staticSurfaceSize.
        auto statU = std::make_unique<JCheckBox>(m_graph, "", 30.f); JCheckBox* stat = statU.get();
        stat->setChecked(!es.staticSurfaceSize());
        stat->onStateChanged.connect([](bool fit) { EditorSettings::instance().setStaticSurfaceSize(!fit); });
        // WHAT THE MAXIMISE BUTTON MEANS. Filling the whole tab is what one is expected to do; the other
        // answer stops beside the live strip and the channel rail so those stay readable with a page
        // maximised. Both are defensible, which is why it is asked here rather than decided in the code.
        auto maxU = std::make_unique<JCheckBox>(m_graph, "", 30.f); JCheckBox* maxb = maxU.get();
        maxb->setChecked(es.maximiseFillsTab());
        maxb->onStateChanged.connect([](bool on) { EditorSettings::instance().setMaximiseFillsTab(on); });
        auto cwU = std::make_unique<JSpinBox>(m_graph, 320, 7680, 100.f); JSpinBox* cw = cwU.get(); cw->setValue(es.canvasWidth());
        auto chU = std::make_unique<JSpinBox>(m_graph, 240, 4320, 100.f); JSpinBox* ch = chU.get(); ch->setValue(es.canvasHeight());
        cw->onValueChanged.connect([cw, ch](int) { EditorSettings::instance().setCanvasSize(cw->value(), ch->value()); });
        ch->onValueChanged.connect([cw, ch](int) { EditorSettings::instance().setCanvasSize(cw->value(), ch->value()); });

        // NO ANCHOR SETTING. A surface fills the space it is given now, so there is no leftover room for it
        // to be aligned within and nothing for the setting to mean. It was a real choice when a surface was
        // a fixed-size card floating in a larger area; it stopped being one when the card went.

        // Canvas-size resolution combo: "Current Display" + a standard-resolution table
        // + "Custom". Picking a preset drives the width/height spins (which persist via setCanvasSize); "Custom"
        // (0×0) leaves the spins for hand-entry. Label = "AR - WxH[ - std]" (aspect ratio via gcd), like fmtRes.
        struct Res { int w, h; const char* std; };
        static const Res kRes[] = {
            {640,480,"VGA"}, {800,600,"SVGA"}, {1024,768,"XGA"}, {1280,720,"WXGA / 720p"}, {1280,800,"WXGA"},
            {1280,1024,"SXGA"}, {1600,900,"HD+"}, {1600,1200,"UXGA"}, {1920,1080,"FHD / 1080p"}, {1920,1200,"WUXGA"},
            {2560,1440,"QHD / 1440p"}, {3440,1440,"WQHD"}, {3840,2160,"4K UHD"}, {7680,4320,"8K UHD"},
        };
        auto fmtRes = [](int w, int h, const char* std) -> std::string {
            int a = w, b = h; while (b) { int t = b; b = a % b; a = t; }   // gcd -> aspect ratio
            std::string s = std::to_string(w / a) + ":" + std::to_string(h / a) + " - " + std::to_string(w) + "x" + std::to_string(h);
            if (std && *std) { s += " - "; s += std; }
            return s;
        };
        std::vector<std::string> canvasLabels;
        auto canvasSizes = std::make_shared<std::vector<std::pair<int,int>>>();
        const auto desk = m_window->virtualDesktopSize();
        if (surfaceAreaFn) {
            const auto area = surfaceAreaFn();
            if (area.first > 0 && area.second > 0) {
                canvasLabels.push_back("Fit Surface Area: " + fmtRes(area.first, area.second, ""));
                canvasSizes->push_back(area);
            }
        }
        canvasLabels.push_back("Current Display: " + fmtRes(desk.first, desk.second, ""));
        canvasSizes->push_back({ desk.first, desk.second });
        for (const Res& r : kRes) { canvasLabels.push_back(fmtRes(r.w, r.h, r.std)); canvasSizes->push_back({ r.w, r.h }); }
        canvasLabels.push_back("Custom"); canvasSizes->push_back({ 0, 0 });
        auto canvasU = std::make_unique<JComboBox>(m_graph, canvasLabels); JComboBox* canvas = canvasU.get();
        int csel = static_cast<int>(canvasSizes->size()) - 1;                 // default to Custom
        for (size_t i = 0; i < canvasSizes->size(); ++i)
            if ((*canvasSizes)[i].first == es.canvasWidth() && (*canvasSizes)[i].second == es.canvasHeight()) { csel = static_cast<int>(i); break; }
        canvas->setCurrentIndex(csel);
        canvas->onIndexChanged.connect([cw, ch, canvasSizes](int i) {
            if (i < 0 || i >= static_cast<int>(canvasSizes->size())) return;
            const auto sz = (*canvasSizes)[i];
            if (sz.first > 0) { cw->setValue(sz.first); ch->setValue(sz.second); EditorSettings::instance().setCanvasSize(sz.first, sz.second); }
        });

        f->add(std::make_unique<JLabel>(m_graph, "Grid size (px)", 150.f));      f->add(std::move(gridU));
        f->add(std::make_unique<JLabel>(m_graph, "Show the grid", 150.f));       f->add(std::move(showU));
        f->add(std::make_unique<JLabel>(m_graph, "Snap to grid", 150.f));        f->add(std::move(snapGU));
        f->add(std::make_unique<JLabel>(m_graph, "Snap to widgets", 150.f));     f->add(std::move(snapWU));
        f->add(std::make_unique<JLabel>(m_graph, "Squeeze pages to fit the window", 150.f)); f->add(std::move(statU));
        f->add(std::make_unique<JLabel>(m_graph, "Maximise fills the whole tab", 150.f));   f->add(std::move(maxU));

        // SAY WHEN IT APPLIES, because it does not apply to what you are looking at. This was labelled
        // "Canvas size" in a general Editor pane, which reads as a property of the pages on screen — and
        // it is not one: every page in a document states its own size, and a converted page reflows to
        // the window and has no canvas at all. Changing this touches neither. It is the nominal page a
        // NEW page is created at, and the width the .ini importer lays its dialogs out to; it is not a
        // zoom, which is what Appearance ▸ Interface scale is for.
        f->add(std::make_unique<JLabel>(m_graph, "Authoring canvas", 150.f));    f->add(std::move(canvasU));
        f->add(std::make_unique<JLabel>(m_graph, "Canvas width", 150.f));        f->add(std::move(cwU));
        f->add(std::make_unique<JLabel>(m_graph, "Canvas height", 150.f));       f->add(std::move(chU));
        f->add(std::make_unique<JLabel>(m_graph, "", 150.f));
        {
            // WRAPPED, or the sentence explaining the setting is itself cut off mid-word — which would be
            // a poor advertisement for a note about things not fitting.
            addNote(f, 3,
                "The canvas a page is EDITED against, and the size a new page is created at. Reading a "
                "page ignores it: pages take the window and arrange themselves into it. An imported "
                ".ini ignores it too, so the same file gives the same document on any machine. To make "
                "everything bigger or smaller, use Appearance > Interface scale.");   // plain '>': U+25B8 is not in the atlas
        }
        // Save-on-close behaviour — resets (or mirrors) the save-changes prompt's "remember" choice.
        f->add(std::make_unique<JLabel>(m_graph, "On exit with unsaved changes", 150.f));
        JComboBox* onExit = f->add(std::make_unique<JComboBox>(m_graph, std::vector<std::string>{ "Ask", "Always save", "Always discard" }));
        onExit->setCurrentIndex(std::clamp(JSettings::instance().get<int>("saveOnExit", 0), 0, 2));
        onExit->onIndexChanged.connect([](int i){ JSettings::instance().set("saveOnExit", i); });
        m_rows[3] = 11;
    }

    // Editor→Widget Defaults: MASTER-DETAIL. The master is a list of widget types; the detail is the ONE real
    // property inspector (PropertiesDock) pointed at a live PROTOTYPE instance of the selected type. Editing a
    // prototype's properties IS editing that type's creation defaults — no bespoke form. On a new widget the
    // prototype's props (minus uid/x/y) are copied over (persisted here into EditorSettings::widgetDefaultProps).
    void buildWidgetDefaults() {
        using namespace jf;
        m_wdefModel = std::make_unique<PanelModel>();
        std::vector<std::string> labels;
        for (const std::string& t : widgetTypes()) {
            m_types.push_back(t);
            const std::string title = widgetTitle(t);
            labels.push_back(title.empty() ? t : title);
            int dw = 160, dh = 90;
            if (auto proto = makeWidgetInstance(t, m_graph)) { dw = static_cast<int>(proto->defaultW()); dh = static_cast<int>(proto->defaultH()); }
            EditorSettings::instance().widgetDefaultSize(t, dw, dh);   // stored size overrides the class default
            m_wdefElem[t] = m_wdefModel->add(t, 0.f, 0.f, static_cast<float>(dw), static_cast<float>(dh),
                                             EditorSettings::instance().widgetDefaultProps(t));   // seed the prototype
        }
        m_typeList = std::make_unique<JListView>(m_graph, labels);
        m_typeList->onSelectionChanged.connect([this](int i) { if (i >= 0 && i < static_cast<int>(m_types.size())) m_wdefPending = m_types[i]; });

        m_wdefProps = std::make_unique<PropertiesDock>(m_graph);
        // Every edit persists the prototype's props as the type's defaults (no undo stack, no surface).
        m_wdefProps->onApplyEdit = [this](const std::string&, const std::vector<PanelElement>&, int){ persistPrototype(m_wdefCurrentType); };

        if (!m_types.empty()) { m_typeList->setSelectedIndex(0); m_wdefPending = m_types[0]; }
    }

    // Point the detail inspector at the selected type's prototype element (deferred out of the click handler).
    void showWidgetDefault(const std::string& type) {
        m_wdefCurrentType = type;
        auto it = m_wdefElem.find(type);
        if (it != m_wdefElem.end() && m_wdefProps) m_wdefProps->showFor(m_wdefModel.get(), { it->second }, true);
    }

    // Serialise the edited prototype back to the type's stored defaults: props (minus geometry/uid/empties) and size.
    void persistPrototype(const std::string& type) {
        if (type.empty() || !m_wdefModel) return;
        auto it = m_wdefElem.find(type);
        if (it == m_wdefElem.end()) return;
        const PanelElement* e = m_wdefModel->get(it->second);
        if (!e) return;
        std::unordered_map<std::string, std::string> props;
        for (const auto& [k, v] : e->props)
            if (k != "x" && k != "y" && k != "w" && k != "h" && k != "uid" && !v.empty()) props[k] = v;
        EditorSettings::instance().setWidgetDefaultProps(type, props);
        EditorSettings::instance().setWidgetDefaultSize(type, static_cast<int>(e->w), static_cast<int>(e->h));
    }

    // Fill a Form container with a widget type's creation-default controls: the default size, then one row per
    // editable property of the widget CLASS's JPropertyModel (order-sorted). Ownership goes into the passed
    // vectors. Returns row count. The TABLES page only — Widget Defaults drives a prototype element through the
    // shared inspector instead. A stored EditorSettings default overrides
    // the class's authored default (JPropertyMeta.def) for the initial value.
    int fillSchemaControls(jf::JContainer* form, const std::string& type) {
        using namespace jf;
        static JSceneGraph s_protoGraph;
        std::unique_ptr<CanvasWidget> proto = makeWidgetInstance(type, s_protoGraph);
        if (!proto) return 0;
        // A PROTOTYPE: constructed only to read its class defaults + property model, never laid out or
        // painted. It still registers in the global widget set, so keep it out of focus/hit scans.
        proto->setScanExcluded(true);
        int rows = 0;
        // Default width / height — the widget class's drop size, overridden by any stored Widget-Defaults size.
        int dw = static_cast<int>(proto->defaultW()), dh = static_cast<int>(proto->defaultH());
        EditorSettings::instance().widgetDefaultSize(type, dw, dh);
        form->add(std::make_unique<JLabel>(m_graph, "Default width", 150.f));
        JSpinBox* wp = form->add(std::make_unique<JSpinBox>(m_graph, 1, 10000, 100.f)); wp->setValue(dw); rows++;
        form->add(std::make_unique<JLabel>(m_graph, "Default height", 150.f));
        JSpinBox* hp = form->add(std::make_unique<JSpinBox>(m_graph, 1, 10000, 100.f)); hp->setValue(dh); rows++;
        auto commitSize = [wp, hp, type] { EditorSettings::instance().setWidgetDefaultSize(type, wp->value(), hp->value()); };
        wp->onValueChanged.connect([commitSize](int){ commitSize(); });
        hp->onValueChanged.connect([commitSize](int){ commitSize(); });

        // Per-property creation defaults from the widget class's JPropertyModel, sorted by meta.order.
        const auto stored = EditorSettings::instance().widgetDefaultProps(type);
        std::vector<JProperty> props = proto->properties().all();
        std::stable_sort(props.begin(), props.end(), [](const JProperty& a, const JProperty& b){ return a.meta.order < b.meta.order; });
        for (const JProperty& p : props) {
            if (!p.writable()) continue;
            const std::string& k = p.name;
            if (k=="x"||k=="y"||k=="w"||k=="h"||k=="uid"||k=="value"||k=="aspectRatioLocked") continue;
            if (k=="labelText"||k=="text"||k=="buttonText"||k=="title") continue;
            const std::string& ed = p.meta.editor;
            if (ed=="signal"||ed=="unit"||ed=="file") continue;
            const auto sit = stored.find(k);
            const std::string v = (sit != stored.end()) ? sit->second : p.meta.def;
            const std::string lbl = p.meta.label.empty() ? k : p.meta.label;
            const std::string key = k;
            if (ed == "color") {
                form->add(std::make_unique<JLabel>(m_graph, lbl, 150.f));
                JColorButton* cbp = form->add(std::make_unique<JColorButton>(m_graph, 170.f));
                cbp->setInheritable(p.meta.inheritable); cbp->setColorHex(v);
                cbp->onColorChanged.connect([key, type](const std::string& hex){ auto m = EditorSettings::instance().widgetDefaultProps(type); m[key] = hex; EditorSettings::instance().setWidgetDefaultProps(type, m); });
                rows++;
            } else if (ed == "font") {
                form->add(std::make_unique<JLabel>(m_graph, lbl, 150.f));
                JFontButton* fbp = form->add(std::make_unique<JFontButton>(m_graph, 170.f));
                fbp->setInheritable(p.meta.inheritable); fbp->setFontSpec(v);
                fbp->onFontChanged.connect([key, type](const std::string& spec){ auto m = EditorSettings::instance().widgetDefaultProps(type); m[key] = spec; EditorSettings::instance().setWidgetDefaultProps(type, m); });
                rows++;
            } else if (!p.meta.choices.empty() || ed == "choices") {
                std::vector<std::string> choices; for (const JVariant& cv : p.meta.choices) choices.push_back(cv.toString());
                if (choices.empty()) continue;
                int idx = 0; try { idx = std::stoi(v); } catch (...) { for (size_t kk=0;kk<choices.size();++kk) if (choices[kk]==v) idx=static_cast<int>(kk); }
                form->add(std::make_unique<JLabel>(m_graph, lbl, 150.f));
                JComboBox* cp = form->add(std::make_unique<JComboBox>(m_graph, choices));
                cp->setCurrentIndex(std::clamp(idx, 0, static_cast<int>(choices.size())-1));
                cp->onIndexChanged.connect([key, type](int i){ auto m = EditorSettings::instance().widgetDefaultProps(type); m[key] = std::to_string(i); EditorSettings::instance().setWidgetDefaultProps(type, m); });
                rows++;
            } else if (p.get().isBool()) {
                form->add(std::make_unique<JLabel>(m_graph, lbl, 150.f));
                JCheckBox* c = form->add(std::make_unique<JCheckBox>(m_graph, "", 30.f)); c->setChecked(v=="1"||v=="true");
                c->onStateChanged.connect([key, type](bool on){ auto m = EditorSettings::instance().widgetDefaultProps(type); m[key] = on?"1":"0"; EditorSettings::instance().setWidgetDefaultProps(type, m); });
                rows++;
            } else if (p.get().isNumber()) {
                form->add(std::make_unique<JLabel>(m_graph, lbl, 150.f));
                JSpinBox* spp = form->add(std::make_unique<JSpinBox>(m_graph, static_cast<int>(p.meta.min.toDouble(0)), static_cast<int>(p.meta.max.toDouble(100)), 100.f));
                int iv = 0; try { iv = static_cast<int>(std::stod(v)); } catch (...) {} spp->setValue(iv);
                spp->onValueChanged.connect([key, type](int nv){ auto m = EditorSettings::instance().widgetDefaultProps(type); m[key] = std::to_string(nv); EditorSettings::instance().setWidgetDefaultProps(type, m); });
                rows++;
            }
            // else: a plain-text property — the old form rendered no control for these; skip (unchanged).
        }
        return rows;
    }

    void buildTables() {   // Editor→Tables: the Table type's creation defaults (same schema form).
        using namespace jf;
        m_tablesScroll = std::make_unique<JScrollArea>(m_graph);
        { float tw, th; if (!widgetDefaultSize("table", tw, th)) return; }   // no "table" widget class → nothing to show
        auto formU = std::make_unique<JContainer>(m_graph);
        JContainer* form = formU.get();
        form->setLayoutMode(JLayoutMode::Form)->setGap(gapV())->setPadding(JEdges{ padV(), padV(), padV(), padV() });
        m_tablesRows = fillSchemaControls(form, "table");
        form->setBounds({ 0.f, 0.f, 300.f, padV()*2.f + (m_tablesRows + 2) * (rowH() + gapV()) });
        m_tablesScroll->addChildWidget(std::move(formU));
    }

    // Editor→Globals: what a property set to "global" actually resolves to. Built from the property model +
    // TableWidget::globalDefs(), so a new "global" property appears here on its own — the alternative was a
    // hand-kept form, which is how the old resolution rule ended up hand-copied into three places.
    // The stored value is the property's OWN choice index (1..N), so the combo lists choices[1..] and the
    // "global" entry itself is dropped — picking "global" as the answer to "what does global mean" is the
    // circularity this page exists to remove.
    void buildGlobals() {
        using namespace jf;
        m_globalsScroll = std::make_unique<JScrollArea>(m_graph);
        static JSceneGraph s_protoGraph;
        std::unique_ptr<CanvasWidget> proto = makeWidgetInstance("table", s_protoGraph);
        if (!proto) return;
        proto->setScanExcluded(true);
        auto formU = std::make_unique<JContainer>(m_graph);
        JContainer* form = formU.get();
        form->setLayoutMode(JLayoutMode::Form)->setGap(gapV())->setPadding(JEdges{ padV(), padV(), padV(), padV() });

        std::vector<JProperty> props = proto->properties().all();
        std::stable_sort(props.begin(), props.end(), [](const JProperty& a, const JProperty& b){ return a.meta.order < b.meta.order; });
        m_globalsRows = 0;
        for (const JProperty& p : props) {
            if (p.meta.choices.empty()) continue;
            std::vector<std::string> choices; for (const JVariant& cv : p.meta.choices) choices.push_back(cv.toString());
            if (choices.size() < 2 || choices[0] != "global") continue;   // only properties that OFFER "global"

            const std::string key = p.name;
            const int def = TableWidget::globalDefault(key.c_str());
            // A global whose default is 0 answers "follow" rather than a fixed choice (the axis decimals
            // follow the cell's). That answer is offered here as a value — visible and changeable — instead
            // of being a second, hidden meaning of the word "global".
            const bool follows = (def == 0);
            std::vector<std::string> opts;
            if (follows) opts.push_back("follow the cell");
            for (size_t i = 1; i < choices.size(); ++i) opts.push_back(choices[i]);

            const int stored = EditorSettings::instance().propGlobal("table." + key, def);
            // store value v == choices[v]; with a "follow" entry at 0 the combo indexes line up, otherwise
            // the combo is shifted by the dropped "global" entry.
            const int idx = follows ? stored : stored - 1;

            form->add(std::make_unique<JLabel>(m_graph, p.meta.label.empty() ? key : p.meta.label, 150.f));
            JComboBox* cp = form->add(std::make_unique<JComboBox>(m_graph, opts));
            cp->setCurrentIndex(std::clamp(idx, 0, static_cast<int>(opts.size()) - 1));
            cp->onIndexChanged.connect([key, follows](int i) {
                EditorSettings::instance().setPropGlobal("table." + key, follows ? i : i + 1);
            });
            m_globalsRows++;
        }
        form->setBounds({ 0.f, 0.f, 300.f, padV()*2.f + (m_globalsRows + 1) * (rowH() + gapV()) });
        m_globalsScroll->addChildWidget(std::move(formU));
    }

    void buildPanelDefaults() {   // Editor→Panel Defaults: new-panel border/title style, stored in EditorSettings.
        using namespace jf;
        m_panelScroll = std::make_unique<JScrollArea>(m_graph);
        auto formU = std::make_unique<JContainer>(m_graph);
        JContainer* form = formU.get();
        form->setLayoutMode(JLayoutMode::Form)->setGap(gapV())->setPadding(JEdges{ padV(), padV(), padV(), padV() });
        auto putKey = [](const std::string& k, const std::string& v) { auto m = EditorSettings::instance().panelDefaultProps(); m[k] = v; EditorSettings::instance().setPanelDefaultProps(m); };
        const auto stored = EditorSettings::instance().panelDefaultProps();
        auto sget = [&](const std::string& k, const std::string& dflt) { auto it = stored.find(k); return it != stored.end() ? it->second : dflt; };
        auto ival = [](const std::string& s, int dflt) { try { return std::stoi(s); } catch (...) { return dflt; } };
        int rows = 0;
        form->add(std::make_unique<JLabel>(m_graph, "Border Width", 150.f));
        JSpinBox* bw = form->add(std::make_unique<JSpinBox>(m_graph, 0, 50, 100.f)); bw->setValue(ival(sget("borderWidth","1"), 1));
        bw->onValueChanged.connect([putKey](int v){ putKey("borderWidth", std::to_string(v)); });
        rows++;
        form->add(std::make_unique<JLabel>(m_graph, "Border", 150.f));
        JColorButton* bc = form->add(std::make_unique<JColorButton>(m_graph, 170.f)); bc->setInheritable(true); bc->setColorHex(sget("borderColor",""));
        bc->onColorChanged.connect([putKey](const std::string& h){ putKey("borderColor", h); });
        rows++;
        form->add(std::make_unique<JLabel>(m_graph, "Border Radius", 150.f));
        JSpinBox* br = form->add(std::make_unique<JSpinBox>(m_graph, 0, 80, 100.f)); br->setValue(ival(sget("borderRadius","4"), 4));
        br->onValueChanged.connect([putKey](int v){ putKey("borderRadius", std::to_string(v)); });
        rows++;
        form->add(std::make_unique<JLabel>(m_graph, "Title Colour", 150.f));
        JColorButton* tc = form->add(std::make_unique<JColorButton>(m_graph, 170.f)); tc->setInheritable(true); tc->setColorHex(sget("titleColor",""));
        tc->onColorChanged.connect([putKey](const std::string& h){ putKey("titleColor", h); });
        rows++;
        form->add(std::make_unique<JLabel>(m_graph, "Title Font", 150.f));
        JFontButton* tf = form->add(std::make_unique<JFontButton>(m_graph, 170.f)); tf->setInheritable(true); tf->setFontSpec(sget("titleFont",""));
        tf->onFontChanged.connect([putKey](const std::string& s){ putKey("titleFont", s); });
        rows++;
        form->add(std::make_unique<JLabel>(m_graph, "Layout", 150.f));
        JComboBox* lay = form->add(std::make_unique<JComboBox>(m_graph, std::vector<std::string>{ "Free","Y Axis","X Axis","Border","Card","Index Card","Grid" }));
        lay->setCurrentIndex(std::clamp(ival(sget("layout","0"), 0), 0, 6));
        lay->onIndexChanged.connect([putKey](int i){ putKey("layout", std::to_string(i)); });
        rows++;
        m_panelRows = rows;
        form->setBounds({ 0.f, 0.f, 300.f, padV()*2.f + (rows + 2) * (rowH() + gapV()) });
        m_panelScroll->addChildWidget(std::move(formU));
    }

    void selectUnit(jf::JComboBox* combo, const std::vector<std::string>& ids, const std::string& pref) {
        for (size_t i = 0; i < ids.size(); ++i) if (ids[i] == pref) { combo->setCurrentIndex(static_cast<int>(i)); return; }
        if (!ids.empty()) combo->setCurrentIndex(0);
    }
    void refreshUnitCombos() {
        for (auto& r : m_unitRows) selectUnit(r.combo, r.ids, UnitManager::instance().preferredUnit(r.qId));
    }

    void _render(jf::JPrimitiveBuffer& buf, float mx, float my, float btnY, float closeX) {
        using namespace jf;
        const float W = static_cast<float>(m_window->width()), H = static_cast<float>(m_window->height());
        const float radius = JStyle::current().cornerRadius;
        buf.pushRectangle(0.f, 0.f, W, H, Colors::Surface0, radius, 1.f, Colors::Border);   // theme surfaces so the dialog matches the app
        // Title bar — the framework's ONE canonical styled bar + close button. No custom chrome.
        const JRect closeR = JCloseButton::rectFor({ 0.f, 0.f, W, hdrH() });
        JTitleBar::draw(buf, 0.f, 0.f, W, hdrH(), "Preferences", radius, 0, 14.f, closeR.width + 14.f);
        JCloseButton::draw(buf, closeR, JCloseButton::hit(closeR, mx, my));
        const float lh = JTextHelper::lineHeight();
        const bool atlas = JTextHelper::hasAtlas();
        // Left nav rail.
        buf.pushRectangle(0.f, hdrH(), kNavW, H - hdrH(), Colors::Surface1, 0.f);
        // The list widget paints the rail: selection, hover and the focus ring, all themed.
        if (nav_) {
            nav_->setBounds(navRect());
            nav_->populateRenderPrimitives(buf);
        }
        // Active page. The Editor page has a sub-tab bar; other backed pages render their scroll area; the
        // pending pages show a note. The framework's JScrollArea owns clipping + scrollbar throughout.
        if (m_page == 3) {
            const JRect cr = contentRect();
            if (editorTabs_) {                       // the tab bar paints itself (active tab, hover, focus)
                editorTabs_->setBounds({ cr.x, cr.y, cr.width, kSubTabH });
                editorTabs_->populateRenderPrimitives(buf);
            }
            if (m_editorTab == 0 && m_scrolls[3]) m_scrolls[3]->populateRenderPrimitives(buf);
            else if (m_editorTab == 1 && m_tablesScroll) m_tablesScroll->populateRenderPrimitives(buf);
            else if (m_editorTab == 3 && m_panelScroll)  m_panelScroll->populateRenderPrimitives(buf);
            else if (m_editorTab == 4 && m_globalsScroll) m_globalsScroll->populateRenderPrimitives(buf);
            else if (m_editorTab == 2 && m_typeList && m_wdefProps) { m_typeList->populateRenderPrimitives(buf); m_wdefProps->populateRenderPrimitives(buf); }
        } else if (m_scrolls[m_page]) {   // Units / Appearance / Connection / Logging
            m_scrolls[m_page]->populateRenderPrimitives(buf);
        }
        // Close button — the primary action, through the PrimaryBtn* role (not a hand-picked Accent/Success).
        if (m_closeBtn) {                      // the widget paints itself (hover/pressed/focus states included)
            m_closeBtn->setBounds({ closeX, btnY, kBtnW, kBtnH() });
            m_closeBtn->populateRenderPrimitives(buf);
        }
    }

    struct UnitRow { jf::JComboBox* combo; std::vector<std::string> ids; std::string qId; };

    std::unique_ptr<PlatformWinType> m_window;
    jf::GpuSurfaceId m_surface{ 0 };
    jf::JSceneGraph  m_graph;
    std::unique_ptr<jf::JContainer> m_pages[kPageCount];
    std::vector<jf::JKeySequenceEdit*>        m_keyEdits;   // Keyboard-page capture rows (non-owning; owned by the page container)
    std::vector<UnitRow> m_unitRows;
    std::unique_ptr<jf::JScrollArea> m_scrolls[kPageCount];   // framework scroll viewport per backed page
    std::vector<std::string> m_portIds;   // parallel to the Serial port combo; "" = Automatic
    int   m_rows[kPageCount]{};      // form rows per page (for the natural-height the scroll area scrolls over)
    uint32_t m_lastW{ kW }, m_lastH{ kH };   // track WM-driven resizes to refresh the surface
    jf::JLabel* m_datalogCost = nullptr;         // Datalog page: the live "what it costs" line
    std::vector<std::pair<int, jf::JLabel*>> m_notes;   // (page, wrapped note) — refit to their width each frame
    jf::JContainer* m_pageRaw[kPageCount]{};             // the pages, once their scroll areas own them
    std::unique_ptr<jf::JListView> nav_;         // left rail — a real list, not painted rows
    std::unique_ptr<jf::JTabBar>   editorTabs_;  // Editor sub-tabs — a real tab bar
    bool  m_focusSeeded{ false };   // initial focus given on the first frame
    int   m_page{ 0 };
    jf::JButton* m_appFontBtn{ nullptr };   // Application Font row: label = current font; refreshed on change
    std::string  m_appFontSeen;             // last ui.font path reflected on the button (change-guard)
    // Editor page sub-tabs + Widget Defaults (a generic form over each widget class's JPropertyModel).
    int   m_editorTab{ 0 };
    jf::JFocusManager                m_focus;   // this dialog's keyboard focus (routes keys to the focused control)
    std::unique_ptr<jf::JListView>   m_typeList;
    std::unique_ptr<PanelModel>      m_wdefModel;   // prototype elements — one per widget type (the "instances")
    std::unique_ptr<PropertiesDock>  m_wdefProps;   // the ONE inspector, pointed at the selected prototype
    std::unordered_map<std::string, int> m_wdefElem;   // type → its prototype element id in m_wdefModel
    std::string                      m_wdefCurrentType;
    std::vector<std::string> m_types;                          // widget type keys, parallel to the list items
    std::string m_wdefPending;                                 // deferred detail-switch target (set from click handlers)
    std::unique_ptr<jf::JScrollArea> m_tablesScroll, m_panelScroll;   // Editor→Tables / →Panel Defaults sub-tabs
    std::unique_ptr<jf::JScrollArea> m_globalsScroll;                 // Editor→Globals sub-tab
    int m_globalsRows = 0;
    int m_tablesRows{ 0 }, m_panelRows{ 0 };
    std::unique_ptr<jf::JButton> m_closeBtn;   // real widget: arm-on-press, fire-on-release-inside
    bool  m_closeArmed{ false };              // title-bar ✕ (a draw helper) armed by a press
    bool  m_done{ false }, m_drag{ false };
    float m_ax{ 0 }, m_ay{ 0 };
};
