#!/bin/bash
# Generates firmware/version.h with the firmware version + git hash.
# No build number / bump: the identity is version + short git hash (with -dirty when the
# working tree has uncommitted changes). The signature is "jayecu <board> <version> <hash>"
# (the firmware appends the layout_hash on the wire).

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

BOARD_PROFILE="${1:-jaytek_v1}"           # target board (matches schema/boards/<name>.board.yaml)
FW_VERSION=$(cat firmware/version.txt 2>/dev/null || echo "0.1.0")

# THE FIRMWARE'S OWN HASH, not the repository's. The studio lives in this repository too, so HEAD moves
# with every studio commit; the firmware's identity must not. The hash is the newest commit that touched
# what the image is built from, and -dirty means one of THOSE has uncommitted changes. version.h itself
# is left out of both: this script rewrites it, so counting it made every build after the first report
# -dirty with nothing edited, and a commit that only carried it would have moved the hash.
FW_PATHS=(firmware definition codegen generated third_party cmake ':(exclude)firmware/version.h'
          ':(exclude)firmware/CHANGES.md')   # a change note is not a firmware change (tools/release_notes.py)
GIT_HASH=$(git log -1 --format=%h -- "${FW_PATHS[@]}" 2>/dev/null || true)
[ -n "$GIT_HASH" ] || GIT_HASH="unknown"
if [ -n "$(git status --porcelain -- "${FW_PATHS[@]}" 2>/dev/null || true)" ]; then
    GIT_HASH="${GIT_HASH}-dirty"
fi

# The numeric parts come from the release numbers only: a beta ("0.5.0-beta.1") keeps its full text in
# JAYECU_FIRMWARE_VERSION (and so in the identity the studio reads), but MAJOR/MINOR/PATCH are numbers.
IFS='.' read -r -a VERSION_PARTS <<< "${FW_VERSION%%[-+]*}"
FW_VERSION_MAJOR=${VERSION_PARTS[0]:-0}
FW_VERSION_MINOR=${VERSION_PARTS[1]:-0}
FW_VERSION_PATCH=${VERSION_PARTS[2]:-0}

VERSION_H="firmware/version.h"
TMP_VERSION_H="${VERSION_H}.tmp"

cat <<EOF > "$TMP_VERSION_H"
#pragma once

/**
 * THIS FILE IS AUTOGENERATED BY scripts/update_version.sh
 * DO NOT EDIT MANUALLY.
 */

#define JAYECU_FIRMWARE_VERSION "$FW_VERSION"
#define JAYECU_FIRMWARE_VERSION_MAJOR $FW_VERSION_MAJOR
#define JAYECU_FIRMWARE_VERSION_MINOR $FW_VERSION_MINOR
#define JAYECU_FIRMWARE_VERSION_PATCH $FW_VERSION_PATCH
#define JAYECU_BOARD_PROFILE    "$BOARD_PROFILE"
#define JAYECU_GIT_HASH         "$GIT_HASH"

/* Human firmware identity. Space-separated so "jayecu <board> <version>" is the GUI
 * family tag; the identity reply ('Q') appends the layout_hash for exact matching. */
#define JAYECU_SIGNATURE  "jayecu " JAYECU_BOARD_PROFILE " " \\
                          JAYECU_FIRMWARE_VERSION " " \\
                          JAYECU_GIT_HASH
EOF

if ! cmp -s "$VERSION_H" "$TMP_VERSION_H"; then
    mv "$TMP_VERSION_H" "$VERSION_H"
    echo "Updated $VERSION_H — $BOARD_PROFILE $FW_VERSION ($GIT_HASH)"
else
    rm "$TMP_VERSION_H"
fi
